DocuSign implementation
ProcessMaker/processmaker pull request #3757
Opened 2021-04-13 15:08 UTC by caleeli

This PR includes:
- Ability to register PMFunctions from packages:
```
$manager = app('workflow.FormalExpression');
$manager->registerPMFunction('foo', function ($data, $param1) {
    return 'bar';
);
```
- Enable interstitial ability for CallActivity

2021-04-13 15:22 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-3104b-processmaker.ci.processmaker.net

2021-04-13 15:22 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-3104b-processmaker.ci.processmaker.net

2021-04-13 15:48 UTC, boliviacoca approved these changes

2021-04-13 17:06 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-3104b-processmaker.ci.processmaker.net

2021-04-14 13:48 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-3104b-processmaker.ci.processmaker.net

2021-04-14 13:50 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-3104b-processmaker.ci.processmaker.net

2021-04-14 14:17 UTC, danloa requested changes

2021-04-14 14:17 UTC, danloa commented on ProcessMaker/Models/FormalExpression.php
> +        // Register global PM functions
Specify that this code is used to register functions from packages

2021-04-14 14:17 UTC, danloa commented on ProcessMaker/Repositories/TokenRepository.php
> +        /** @var ProcessRequest $request */
Remove this non standard annotations

2021-04-14 14:30 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-3104b-processmaker.ci.processmaker.net

2021-04-14 14:30 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-3104b-processmaker.ci.processmaker.net

2021-04-14 14:35 UTC, danloa approved these changes

2021-04-14 14:40 UTC, boliviacoca approved these changes

2021-04-14 14:40 UTC, merged

2021-04-14 14:51 UTC, pmkerberos commented
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

2021-04-14 14:52 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-3104b-processmaker.ci.processmaker.net