Notices composer install
ProcessMaker/processmaker pull request #3806
Opened 2021-05-14 14:09 UTC by marcoAntonioNina

Fixed [FOUR-1305](https://processmaker.atlassian.net/browse/FOUR-1305)

- fix namespaces

2021-05-18 21:01 UTC, nolanpro requested changes
@marcoAntonioNina The PMConfigGenericExportManager is still used by packages like actions-by-email so we should probably keep the test

2021-05-18 21:08 UTC, nolanpro approved these changes

2021-05-18 21:12 UTC, boliviacoca approved these changes

2021-05-18 21:25 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-1375-processmaker.ci.processmaker.net

2021-05-19 12:11 UTC, merged

2021-05-19 12:21 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-1375-processmaker.ci.processmaker.net