Add Screen warnings for large number of controls and use if watchers/scripts
ProcessMaker/processmaker pull request #3911
Opened 2021-07-28 19:30 UTC by caleeli

Fixes: https://processmaker.atlassian.net/browse/FOUR-3698

Add Screen warnings for large number of controls and use if watchers/scripts

![ScreenWarningns2](https://user-images.githubusercontent.com/8028650/127384059-b5a78c58-2f5f-4187-8320-8381d058a5b7.jpg)

Example:
[LargeScreen.json.txt](https://github.com/ProcessMaker/processmaker/files/6895994/LargeScreen.json.txt)

2021-07-28 19:37 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-3698-processmaker.ci.processmaker.net

2021-07-28 19:39 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-3698-processmaker.ci.processmaker.net

2021-07-28 19:40 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-3698-processmaker.ci.processmaker.net

2021-07-28 20:04 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-3698-processmaker.ci.processmaker.net

2021-07-28 20:52 UTC, danloa requested changes

2021-07-28 20:52 UTC, danloa commented on resources/js/processes/screen-builder/screen.vue
> +          message: this.$t('We recommend using fewer than 25 form elements in your screen for optimal performance.'),
Add this string to translations

2021-07-28 20:52 UTC, danloa commented on resources/js/processes/screen-builder/screen.vue
> +          message: this.$t('Using watchers with Scripts can slow the performance of your screen.'),
Add this string to translations

2021-07-28 21:10 UTC, caleeli commented on resources/js/processes/screen-builder/screen.vue
> +          message: this.$t('We recommend using fewer than 25 form elements in your screen for optimal performance.'),
Missing translations were added

2021-07-28 21:10 UTC, caleeli commented on resources/js/processes/screen-builder/screen.vue
> +          message: this.$t('Using watchers with Scripts can slow the performance of your screen.'),
Missing translations were added

2021-07-28 21:16 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-3698-processmaker.ci.processmaker.net

2021-07-28 21:16 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-3698-processmaker.ci.processmaker.net

2021-07-29 16:50 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-3698-processmaker.ci.processmaker.net

2021-07-30 15:15 UTC, danloa approved these changes

2021-07-30 15:18 UTC, boliviacoca approved these changes

2021-07-30 15:19 UTC, merged

2021-07-30 15:29 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-3698-processmaker.ci.processmaker.net

2021-07-30 15:29 UTC, pmkerberos commented
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net