Revert "4.1 Remove Request Detail Screen select"
ProcessMaker/processmaker pull request #4160
Opened 2021-11-18 19:05 UTC by ryancooley

Reverts ProcessMaker/processmaker#4044

2021-11-18 19:16 UTC, pmkerberos commented
QA server was successfully deployed https://revert-4044-bugfix-ticket-676-4-1-processmaker.ci.processmaker.net

2021-11-18 21:08 UTC, sanjacornelius commented
Note that when I test a process, the functionality of the Request Detail Screen displaying in the Summary tab after requests have been completed does not work. It didn't work before this change as well hence why we "removed" it. Currently, I can only get the Request Detail Screen to display for requests that are in progress. The End Event Summary page is what seems to control the displayed screen upon completion.

@caleeli can you please let me know if you can get the Request Detail Screen to display for a completed request?

2021-11-18 21:08 UTC, sanjacornelius approved these changes

2021-11-19 16:34 UTC, caleeli requested changes
HI @sanjacornelius @ryancooley actually when a process is completed, this is not displaying the summary configured in Request Detail Screen. This is bug probably introduced when the End Event Summary was implemented.

I was reviewing how that use to work in previous versions, and well, the `Request Detail Screen` should be displayed in the Summary Tab when the process is completed, unless you have an `Summary Screen` configured in your End Event.

So the logic should be:
1. Show `End Event Summary` Screen if defined
2. If End Event Summary Screen is not defined show `Request Detail Screen`
3. if Request Detail Screen is not defined show the `default list of variables and values`

I think this could be fixed reviewing the `resources/views/requests/show.blade.php`
in the function:
```
          /**
           * Get Screen summary
           * */
          screenSummary() {
            return this.request.summary_screen;
          },
```
adding the `this.request.request_detail_screen` to the logic.

2021-11-19 18:20 UTC, ryancooley commented
Per @velkymx this PR meets the product requirements so I am merging as is.

2021-11-19 18:20 UTC, merged