Bugfix FOUR-5061 (4.2) - Console errors in Saved-Search listing when created_by is null
ProcessMaker/processmaker pull request #4237
Opened 2022-01-05 21:58 UTC by eiresendez

## Issue & Reproduction Steps
Console errors are displayed when the user who created the saved search has been deleted.

1. Generate a saved search
2. Delete the user whom created that saved search
3. Go to `/requests/saved-searches` and you will see errors in console

## Solution
- The error is caught when there is no user in the `AvatarImage.vue` component.

## How to Test
1. Generate a saved search.
2. Delete the user whom created that saved search.
3. Go to `/requests/saved-searches` and you won't see errors in console.

## Related Tickets & Packages
- [FOUR-5061](https://processmaker.atlassian.net/browse/FOUR-5061)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2022-01-05 22:09 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-5061-4-2-processmaker.ci.processmaker.net

2022-01-07 14:03 UTC, danloa requested changes
Saved searches are used in Collections too. If the user that created a collection is deleted, the user to which is shared this collection will see a PHP error after the login:
![image](https://user-images.githubusercontent.com/14875032/148554816-7e974f3f-90ba-485f-b08d-a28a508bdef0.png)

2022-01-07 21:08 UTC, danloa approved these changes
Note that we'll need to use this change to be used  in the compilation of package-saved-search

2022-01-13 23:03 UTC, ryancooley approved these changes

2022-01-13 23:04 UTC, merged