When importing a process, screens do not change number
ProcessMaker/processmaker pull request #4239
Opened 2022-01-10 20:14 UTC by marcoAntonioNina

## Issue & Reproduction Steps
After importing a process, the name of the screen does not change when having a screen with the same name.

## Solution
- verify exists new name generated.

## How to Test
- import the process several times and check the names of the generated screens

## Related Tickets & Packages
- [FOUR-5081](https://processmaker.atlassian.net/browse/FOUR-5081)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2022-01-10 20:26 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-5081-processmaker.ci.processmaker.net

2022-01-11 17:53 UTC, danloa reviewed
The PR adds a consecutive number at the end of the last name found:

![image](https://user-images.githubusercontent.com/14875032/148995485-761a12bb-88a9-4680-8ad3-0ab6f5337533.png)

@ryancooley  does it look good for you? I was thinking in other naming schemas like
_aaa
aaa imported
aaa imported imported_
another option:
_aaa
aaa-2
aaa-2-3_

2022-01-13 20:39 UTC, ryancooley requested changes
@marcoAntonioNina This PR should be refactored to use the naming convention found in the `formatName` method of the file ProcessMaker/Jobs/ImportProcess.php, so that it is consistent.

cc: @danloa

2022-01-13 21:02 UTC, ryancooley approved these changes
@marcoAntonioNina Actually, after reviewing this further, I was wrong. You are already using the formatName method. This looks good and I approve.

cc: @danloa

2022-01-13 21:05 UTC, merged