Bugfix FOUR 5119 - Enable pagination in Forms tab when a request is complete
ProcessMaker/processmaker pull request #4252
Opened 2022-01-20 22:00 UTC by eiresendez

## Issue & Reproduction Steps
Can't see all the records within a record list when a request is completed.

1. Create a screen with only a record list control
2. Add one column named ID to the record list
3. Create a new page in order to add values to the record list
4. add a line input with ID as the variable
5. in the first page check the Editable option and choose the new page in the record form field
6. create a process with one task and add the screen to this task.
7. start a new request
8. add more than 5 rows to the records list.
9. submit the screen, it will be set as completed.
10. try to check the second page in the record list, is not possible.

## Solution
- The component had a CSS rule that prevented pagination from working properly.

## How to Test
Please follow the reproduction steps of above in order to test the solution. You should see the following result:

https://user-images.githubusercontent.com/90741874/150428840-9da72426-338b-4b25-b2c4-3db828d3e92c.mov

## Related Tickets & Packages
- [FOUR-5119](https://processmaker.atlassian.net/browse/FOUR-5119)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2022-01-21 16:16 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-5119-4-2-processmaker.ci.processmaker.net

2022-01-21 16:53 UTC, marcoAntonioNina approved these changes

2022-01-21 18:17 UTC, marcoAntonioNina requested changes
I think that all the information in the record list should be shown and the pagination should be removed.

2022-01-21 22:16 UTC, pmkerberos commented
QA server was successfully deployed https://bugfix-four-5119-4-2-processmaker.ci.processmaker.net

2022-01-24 16:35 UTC, marcoAntonioNina approved these changes

2022-01-28 21:10 UTC, ryancooley approved these changes

2022-01-28 21:11 UTC, merged