Updates for ci (WIP)
ProcessMaker/processmaker pull request #4273
Opened 2022-02-01 19:17 UTC by nolanpro

Placeholder to trigger github actions. Do not merge yet.

2022-02-18 15:51 UTC, danloa requested changes

2022-02-18 15:51 UTC, danloa commented on tests/Feature/ClearRequestsTest.php
> +        $currrentProcessIds = Process::pluck('id');
typo: 3rs (currrent) instead of 2 (current)

2022-02-18 15:51 UTC, danloa commented on tests/Feature/OnSiteStorage/OnSiteStorageMigrationsTest.php
> +        // We no longer support separate databases
Wouldn't be better to remove this test?

2022-04-18 20:21 UTC, agustinbusso approved these changes

2022-04-19 20:17 UTC, pmkerberos commented
QA server was successfully deployed https://ci-2baae70640.eng.processmaker.net

2022-04-22 05:20 UTC, ryancooley approved these changes

2022-04-22 05:20 UTC, merged