Add favicon to list of images that can be customized in the Customize UI page
ProcessMaker/processmaker pull request #4342
Opened 2022-04-18 19:50 UTC by ryancooley

## Issue & Reproduction Steps
As an administrator, I want the ability to set the favicon to a custom PNG image, similarly to how I can set the three custom logos currently.

## Solution
To accommodate this, we will simply add a fourth option to the list of icons allowed to be customized via the Customize UI page. We will then reference this custom icon in the primary layout blade template.

## How to Test
1. Visit the Customize UI page
2. Upload a new transparent PNG via the Custom Favicon file upload control
3. Click **Save** to save changes
4. Refresh the page and check to see
    4a. If the source code reflects the new custom favicon after the title tag
    4b. If the favicon has changed in the browser

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-5964

## Code Review Checklist
- [x] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [x] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [x] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [x] This solution fixes the bug reported in the original ticket.
- [x] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [x] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [x] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [x] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [x] This ticket conforms to the PRD associated with this part of ProcessMaker.

2022-04-18 20:03 UTC, pmkerberos commented
QA server was successfully deployed https://story-four-5964-processmaker.ci.processmaker.net

2022-04-18 20:05 UTC, pmkerberos commented
QA server was successfully deployed https://story-four-5964-processmaker.ci.processmaker.net

2022-04-19 18:23 UTC, marcoAntonioNina requested changes

2022-04-19 18:23 UTC, marcoAntonioNina commented on resources/js/admin/cssOverride/components/SiteDesign.vue
> +          :label="$t('Custom Favicon')"
falta la etiqueta en el archivo en.json

2022-04-19 21:30 UTC, ryancooley commented on resources/js/admin/cssOverride/components/SiteDesign.vue
> +          :label="$t('Custom Favicon')"
Resolved by #[3dc3176](https://github.com/ProcessMaker/processmaker/pull/4342/commits/3dc3176fc1f061f14cb18c86695e59fe219fb66d)

2022-04-19 21:43 UTC, pmkerberos commented
QA server was successfully deployed https://story-four-5964-processmaker.ci.processmaker.net

2022-04-19 21:46 UTC, marcoAntonioNina approved these changes

2022-04-20 16:23 UTC, pmkerberos commented
QA server was successfully deployed https://story-four-5964-processmaker.ci.processmaker.net

2022-04-22 04:41 UTC, merged