FOUR-5957: Create an upgrade migration to sanitize usernames
ProcessMaker/processmaker pull request #4348
Opened 2022-04-21 16:24 UTC by runyan-co

## Issue & Reproduction Steps
In prior versions of processmaker/processmaker, the username field allowed numerous characters which are now disallowed. The only allowed characters in a username are alphanumeric, the underscore character "_", and the hyphen character "-". 

## Solution
- An upgrade migration is included in this PR which when run, spawns a UsernameSanitization job per 1000 users. It spreads out the workload so the PHP process won't run out of memory in the event there are 25,000+ usernames.
- The UsernameSanitization job removes all disallowed characters and checks to make sure the sanitized username is unique. If it is not unique, it will append a number start with 0 to the end of the username and check for uniqueness again and will loop this behavior until the username is unique. It will then save the username and continue to the next.

## How to Test
1. Create a bunch of dummy users with usernames containing disallowed characters e.g. !@#$%^&*(). You may have to go directly into the database to save this.
2. Run `php artisan upgrade` and check to make sure the jobs are spawned in the queue and have run properly.
3. After the jobs have completed, check the users in the admin dashboard. The usernames should now only contain the allowed characters.

## Related Tickets & Packages
- JIRA [ticket FOUR-5957](https://processmaker.atlassian.net/browse/FOUR-5957)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2022-04-21 16:44 UTC, pmkerberos commented
QA server was successfully deployed https://upgrade-four-5957-processmaker.ci.processmaker.net

2022-04-22 01:58 UTC, pmkerberos commented
QA server was successfully deployed https://upgrade-four-5957-processmaker.ci.processmaker.net

2022-04-22 02:01 UTC, pmkerberos commented
QA server was successfully deployed https://upgrade-four-5957-processmaker.ci.processmaker.net

2022-04-22 13:33 UTC, danloa requested changes

2022-04-22 13:33 UTC, danloa commented on ProcessMaker/Jobs/SanitizeUsernames.php
> +            preg_match_all('/[^A-Za-zÀ-ÖØ-öø-ÿ\d\s_-]/u', $username, $invalid_chars, PREG_SET_ORDER, 0);
This regex is excluding valid characters in chinese or arabic (example: النسر الطائر ). We can improve it with:
`[^\p{L}\p{N}\-_\s]`
where \p{L} -> valid alphabetic, \p{N} -> numeric

2022-04-22 13:33 UTC, danloa commented on ProcessMaker/Jobs/SanitizeUsernames.php
> +        build_username_query:
I think that we can avoid the use of the GOTO construct  with something like:
```
do {
     build_username_query;
     $unique_username_query =  DB::table()...
} while ($unique_username_query->exists())
```

2022-04-22 17:49 UTC, pmkerberos commented
QA server was successfully deployed https://upgrade-four-5957-processmaker.ci.processmaker.net

2022-04-22 19:53 UTC, pmkerberos commented
QA server was successfully deployed https://upgrade-four-5957-processmaker.ci.processmaker.net

2022-04-22 21:17 UTC, pmkerberos commented
QA server was successfully deployed https://upgrade-four-5957-processmaker.ci.processmaker.net

2022-04-22 21:19 UTC, pmkerberos commented
QA server was successfully deployed https://upgrade-four-5957-processmaker.ci.processmaker.net

2022-04-22 21:21 UTC, pmkerberos commented
QA server was successfully deployed https://upgrade-four-5957-processmaker.ci.processmaker.net

2022-04-22 21:50 UTC, pmkerberos commented
QA server was successfully deployed https://upgrade-four-5957-processmaker.ci.processmaker.net

2022-04-22 22:34 UTC, danloa approved these changes

2022-04-22 22:45 UTC, pmkerberos commented
QA server was successfully deployed https://upgrade-four-5957-processmaker.ci.processmaker.net

2022-04-27 23:03 UTC, ryancooley approved these changes

2022-04-27 23:03 UTC, merged