Integrate Gmail API Email Server
ProcessMaker/processmaker pull request #4442
Opened 2022-07-14 18:45 UTC by sanjacornelius

## Issue & Reproduction Steps

Ticket: [FOUR-6104](https://processmaker.atlassian.net/browse/FOUR-6104)

As a System Administrator, I want to enable an email server using the Gmail API so that my platform utilizes my preferred and familiar email service

This PR updates the Settings UI based on the [Email Server PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/2761064449/Email+Server+Options+-+Office365+Modern+Auth+and+Gmail+API) specifications as well as adds a Custom Gmail Driver for Gmail Api support.

## Solution

- Remove Pagination
- Update the placement and verbiage of tab buttons
- Update 'Action' icons
- Adds the 'Gmail' option in the UI for the 'Mailer Driver' Model
- Implements Custom Gmail Driver
- Adds migration 

## UI Updates

**Before**

![Screen Shot 2022-07-14 at 11 07 28 AM](https://user-images.githubusercontent.com/52755494/179053935-eff9820a-472f-45e7-b4a6-a206f9d77759.png)
![Screen Shot 2022-07-14 at 11 07 39 AM](https://user-images.githubusercontent.com/52755494/179053975-d779a316-99ea-4af3-b0ce-61a02b326c9d.png)

**After**
![Screen Shot 2022-07-14 at 11 15 45 AM](https://user-images.githubusercontent.com/52755494/179054016-ab28fa26-4512-431d-b51c-fd18dd1b35f6.png)

![Screen Shot 2022-07-14 at 11 15 52 AM](https://user-images.githubusercontent.com/52755494/179054038-9209974f-036e-488e-8556-69a9f5588300.png)

## How to Test

**Testing UI**
1. Review the [PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/2761064449/Email+Server+Options+-+Office365+Modern+Auth+and+Gmail+API)
1. Ensure the following packages are installed - 
    - Auth Package
    - Send Email Connector - PR (feature/FOUR-6104) 
    - Actions By Email
    - Docusign Connector
2. Run `php artisan migrate` 
3. Within the settings tabs ensure UI displays properly
   - Buttons are displayed properly
   - Add / Remove Email Servers works as expected
   - Configurations Update as expected. etc...

## Related Tickets & Packages
- Ticket: [FOUR-6104](https://processmaker.atlassian.net/browse/FOUR-6104)
- [Email Server PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/2761064449/Email+Server+Options+-+Office365+Modern+Auth+and+Gmail+API)
- Send Email PR (feature/FOUR-6104)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2022-07-15 18:31 UTC, agustinbusso approved these changes
All working as expected.

## UI Tests
Buttons for each section were placed correctly

![Screen Shot 2022-07-15 at 12 33 54](https://user-images.githubusercontent.com/90727999/179286631-eb5d469d-035e-461d-9abf-f8255b57ad98.png)

![Screen Shot 2022-07-15 at 12 34 07](https://user-images.githubusercontent.com/90727999/179286634-ff4c7064-9700-4ed4-aa79-7aaf637cfe4e.png)
![Screen Shot 2022-07-15 at 12 35 23](https://user-images.githubusercontent.com/90727999/179286638-ca274fd9-2a86-4af8-b07b-8089ecc3c046.png)

![Screen Shot 2022-07-15 at 12 33 47](https://user-images.githubusercontent.com/90727999/179286614-efb4fbdf-fe24-4ade-9018-fea0e6420d99.png)

In email server tab all UI improvements were correctly applied (align text for first column, changed icon size to lg, changed buttons styles to outline as specified in the PRD, changed remove server icon for trash), show **Authorize** button only for gmail and office365:

![Screen Shot 2022-07-15 at 12 36 14](https://user-images.githubusercontent.com/90727999/179287121-e5ed13e5-6d8e-42a2-baea-705f5b33616a.png)

Authorized label showing correctly after complete authorization:
![Screen Shot 2022-07-15 at 14 32 08](https://user-images.githubusercontent.com/90727999/179287351-15a6ebaf-fa09-4a11-a8ea-f4eb34fc24cc.png)


## Functionality tests
Test authorization. After click on Authorization button a promp shows asking to allow access to the application:
![Screen Shot 2022-07-15 at 14 30 34](https://user-images.githubusercontent.com/90727999/179287608-14bc9687-bc1e-4ff8-80e7-67da07fce635.png)

After accept, authorized label shows in green:
![Screen Shot 2022-07-15 at 14 32 08](https://user-images.githubusercontent.com/90727999/179287488-43f0b3c3-ca9c-4635-a5f1-02a7a46b5084.png)

Test email server button working as expected:

https://user-images.githubusercontent.com/90727999/179287970-0ff0f0f7-bdb4-4275-b81c-4deec6ad1efd.mov

Test a process with data connector working as expected, also with mustaches:

https://user-images.githubusercontent.com/90727999/179288102-52cc9d8a-13b2-4807-ac7d-26dd82f205bf.mov

2022-07-15 21:13 UTC, caleeli requested changes
Gmail Driver is working really good.
Just hide the Office 365 option, it is throwing and error

2022-07-15 21:13 UTC, caleeli commented on database/migrations/2022_06_22_160857_change_buttons_ui_in_settings_table.php
> +            'ui' => '{"options": ["smtp", "sendmail", "mailgun", "postmark", "ses", "gmail", "office 365"]}',
Since Office 365 is not yet implemented, do not include this option

2022-07-22 17:49 UTC, sanjacornelius commented
Closing this PR. Gmail integration is taking a different direction. Gmail SMTP Oauth will be used to send emails not Gmail API which this PR introduced. The [Email Server PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/2761064449/Email+Server+Options+-+Office365+Modern+Auth+and+Gmail+API) has been updated to reflect these changes.

https://github.com/ProcessMaker/connector-send-email/pull/209

2022-07-22 17:49 UTC, closed without merging