Integrate Office 365 SMTP Email Server
ProcessMaker/processmaker pull request #4470
Opened 2022-08-10 20:34 UTC by sanjacornelius

## Issue & Reproduction Steps

Ticket: [FOUR-6103](https://processmaker.atlassian.net/browse/FOUR-6103)

As a System Administrator, I want to enable an email server using the Office 365 SMTP so that my platform utilizes my preferred and familiar email service

This PR updates the Settings UI based on the [Email Server PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/2761064449/Email+Server+Options+-+Office365+Modern+Auth+and+Gmail+API) specifications as well as adds a new SMTP Authentication Method option allowing users to select either Standard, Google or Office 365 Authentication.

## Solution

- Adds the 'office365' option in the UI for the 'SMTP Authentication Method' Model
- Implements XOAUTH2 for Office 365 SMTP

## UI Updates

**Before**

![Screen Shot 2022-07-14 at 11 07 28 AM](https://user-images.githubusercontent.com/52755494/179053935-eff9820a-472f-45e7-b4a6-a206f9d77759.png)
![Screen Shot 2022-07-14 at 11 07 39 AM](https://user-images.githubusercontent.com/52755494/179053975-d779a316-99ea-4af3-b0ce-61a02b326c9d.png)

**After**

![Screen Shot 2022-08-10 at 9 09 35 AM](https://user-images.githubusercontent.com/52755494/184013948-0b2019de-1fbc-4cb9-a00b-1561a46df0a0.png)

![Screen Shot 2022-08-10 at 9 09 15 AM](https://user-images.githubusercontent.com/52755494/184013984-f9cdf669-dd37-4662-a1ad-323c92dcc437.png)

## How to Test

**Testing UI and Migration**

1. Review the [PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/2761064449/Email+Server+Options+-+Office365+Modern+Auth+and+Gmail+API)
2. Ensure you are on the `develop` branch for both Core and Send Email Connector
3. Ensure the following packages are installed - 
    - Auth Package
    - Send Email Connector  `develop`
    - Actions By Email
    - DocuSign Connector
4. Configure a few Email servers with and without SMTP settings
5. Update Core branch `feature/FOUR-6103B` 
6. Update Send Email Connector branch `feature/FOUR-6103B`
7. Reinstall Packages
4. Run `php artisan migrate`
8. Within the settings tabs ensure UI displays properly as specified in the PRD
   - Buttons are displayed properly
   - Existing Email Servers Configurations display properly
   - Add / Remove Email Servers works as expected
   - Configurations Update as expected. etc...

## Related Tickets & Packages
- Ticket: [FOUR-6103](https://processmaker.atlassian.net/browse/FOUR-6103)
- Ticket: [FOUR-6104](https://processmaker.atlassian.net/browse/FOUR-6104)
- [Email Server PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/2761064449/Email+Server+Options+-+Office365+Modern+Auth+and+Gmail+API)
- [Send Email PR - Google Integration](https://github.com/ProcessMaker/connector-send-email/pull/211) `feature/FOUR-6104B`

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2022-08-12 18:43 UTC, nolanpro requested changes
Here's my suggested changes for both this branch and the package:
- In composer.json, move the Google and Microsoft dependencies to core since they are used there too. 
- Remove require_once  __DIR__ . '/../../vendor/autoload.php'; in EmailController.php controller. It's not needed and often composer install is not run in the package folder.
- Authorize account button should be hidden on standard auth?
- Consistency issues (package and core) with EMAIL_CONNECTOR_OFFICE_* environment variables/settings. Some use an underscore before the index and some don't. We should probably always use the underscore before the index to stay consistent.
- OauthTransportManager:152 is setting $expirationTime to a Carbon object. Although this correctly serializes when stored, it causes scripts to fail because script tasks run escapeshellarg() on it.
- In config/app.php, providers has both MailServiceProvider and OauthMailServiceProvider. OauthMailServiceProvider extends MailServiceProvider and calls its parent registerSwiftTransport(). OauthMailServiceProvider sets a singleton for swift.transport and so does the parent. Since the singleton is overwritten, you can remove the call to parent:: in OauthMailServiceProvider and remove Illuminate\Mail\MailServiceProvider::class from app.php

2022-08-12 23:02 UTC, sanjacornelius commented
@nolanpro  Updates have been made to both PRs. Can you please pull down the latest and retest it?

2022-08-13 00:51 UTC, nolanpro approved these changes

2022-08-15 15:13 UTC, danloa commented on ProcessMaker/Managers/OauthTransportManager.php
> +            throw $error;
as the error is simply re-thrown after the catch,  the try/catch block is unnecesary. Add some error handling (log info, etc.) to keep the try/catch

2022-08-15 15:13 UTC, danloa commented on ProcessMaker/Managers/OauthTransportManager.php
> +                default:
remove the default as there isn't code in it

2022-10-24 23:12 UTC, merged