Bugfix/FOUR-7229: RESET Custom Logo, Icon and Favicon Images does not work
ProcessMaker/processmaker pull request #4598
Opened 2023-01-03 20:13 UTC by agustinbusso

## Issue & Reproduction Steps
- Upload images in this  section of Dynamic UI
- Save
- Click on reset buton

Current Behavior:
Resetting images does not work

Expected Behavior:
Resetting images must work

## Solution
- Use destroy instead delete to delete the setting for css-override when clicking "reset" button

**Working video**

https://user-images.githubusercontent.com/90727999/210433970-0ca0f384-206a-4969-87f0-e2e2b07b1e19.mov

## How to Test
- Follow above steps. Make sure the images are correctly restored to the original

## Related Tickets & Packages
-  [FOUR-7229](https://processmaker.atlassian.net/browse/FOUR-7229)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-01-04 23:59 UTC, nolanpro requested changes

2023-01-04 23:59 UTC, nolanpro commented on tests/Feature/Api/CssOverrideTest.php
>          $this->markTestSkipped('FOUR-6653');
Looks like you fixed the test :) so you can remove markTestSkipped

2023-01-05 16:22 UTC, nolanpro approved these changes

2023-01-18 17:09 UTC, ryancooley approved these changes

2023-01-18 17:09 UTC, merged