Bugfix/four 8091
ProcessMaker/processmaker pull request #4720
Opened 2023-04-27 23:56 UTC by estebangallego

## Issue & Reproduction Steps
We don't have translated labels in the other languages in Process Template.

## Solution
- Add translation for templates.
- Add translations for the Ellipsis menu.

## How to Test
- Log in with another language. Eg: Spanish
- Click on Designer 
- Click on the Templates  tab 
- Click on the ellipsis menu

## Current Behavior: 
- The menu is not translated.

## Expected Behavior:
- The menu should be translated.

## Ticket 
- [FOUR-8091](https://processmaker.atlassian.net/browse/FOUR-8091)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-05-03 20:49 UTC, agustinbusso requested changes
The PR looks great! Only some translations are missing when trying to import an invalid file. Or after import a valid file. Please take a look to the following screenshots:

<img width="1358" alt="Screen Shot 2023-05-03 at 17 44 29" src="https://user-images.githubusercontent.com/90727999/236046233-d558fbf1-fcda-45cb-9e04-68b519255392.png">

<img width="1076" alt="Screen Shot 2023-05-03 at 17 49 13" src="https://user-images.githubusercontent.com/90727999/236046331-c0772879-0ffb-4c50-9af2-c2f73f695d77.png">

2023-05-03 21:22 UTC, estebangallego commented
Hey @agustinbusso I spoke with Bo and yes, we will create a new ticket with the items you were able to find and move forward with the acceptance criterion of this ticket.

2023-05-03 21:45 UTC, agustinbusso approved these changes
The requested changes will be addressed in a new ticket according with the acceptance criteria updated by @estebangallego in sync with @boliviacoca

2023-05-04 04:05 UTC, ryancooley approved these changes

2023-05-04 04:05 UTC, merged