feature/FOUR-8231
ProcessMaker/processmaker pull request #4785
Opened 2023-05-15 18:20 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
N/A

## Solution
N/A

## How to Test
- Go to admin
- Select edit an user
- Go to groups tab
- Change the groups and SAVE
- Check the security_logs table for a new log "groupMembershipChanged"

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-8231

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-05-19 20:58 UTC, pmkerberos commented
QA server was successfully deployed https://ci-3895896475.eng.processmaker.net

2023-05-22 16:58 UTC, pmPaulis requested changes

2023-05-22 16:58 UTC, pmPaulis commented on ProcessMaker/Events/GroupUsersUpdated.php
> +
Add description

2023-05-22 16:58 UTC, pmPaulis commented on ProcessMaker/Events/GroupUsersUpdated.php
> +
Add description

2023-05-22 16:58 UTC, pmPaulis commented on ProcessMaker/Events/UserGroupMembershipUpdated.php
> +        $groups_deleted = [];
Lower camel case groupsDeleted

2023-05-22 16:58 UTC, pmPaulis commented on ProcessMaker/Events/UserGroupMembershipUpdated.php
> +        $groups_added = [];
Lower camel case groupsAdded

2023-05-22 16:58 UTC, pmPaulis commented on ProcessMaker/Events/UserGroupMembershipUpdated.php
> +use Illuminate\Broadcasting\InteractsWithSockets;
This is declared but is not used, check for all

2023-05-22 16:58 UTC, pmPaulis commented on ProcessMaker/Events/GroupUsersUpdated.php
> +use Illuminate\Broadcasting\InteractsWithSockets;
This is declared but is not used, check for all

2023-05-22 16:58 UTC, pmPaulis commented on ProcessMaker/Events/UserGroupMembershipUpdated.php
> +        $this->user = Auth::user();
Remove this line $this->user = Auth::user();

2023-05-22 18:43 UTC, paulosakamoto commented on ProcessMaker/Http/Controllers/Api/UserController.php
> +        event(new UserGroupMembershipUpdated($data, $user));
When there are no groups and the groups are detached we get into a bug situation as `$data` is undefined.

2023-05-22 18:43 UTC, paulosakamoto commented on ProcessMaker/Events/UserGroupMembershipUpdated.php
> +    public function __construct(Array $data, User $userUpdated)
Could you please change `Array` to lowercase?

2023-05-25 16:24 UTC, pmkerberos commented
QA server was successfully deployed https://ci-3895896475.eng.processmaker.net

2023-05-25 16:24 UTC, pmkerberos commented
QA server was successfully deployed https://ci-3895896475.eng.processmaker.net

2023-05-25 16:59 UTC, pmkerberos commented
QA server was successfully deployed https://ci-3895896475.eng.processmaker.net

2023-05-25 17:00 UTC, pmPaulis requested changes

2023-05-25 17:00 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/GroupMemberController.php
> +        event(new GroupUsersUpdated($group->id , $request->input('member_id'), 'added', $request->input('member_type')));
Avoid this hardcoded value 'added'
`GroupUsersUpdated::ADDED`

2023-05-25 17:57 UTC, pmkerberos commented
QA server was successfully deployed https://ci-3895896475.eng.processmaker.net

2023-05-25 18:46 UTC, pmPaulis approved these changes

2023-05-25 18:46 UTC, pmPaulis commented on ProcessMaker/Providers/EventServiceProvider.php
> +        'ProcessMaker\Events\UserGroupMembershipUpdated' => [
Reorder UserGroupMembershipUpdated after UserDeleted

2023-05-25 18:46 UTC, pmPaulis commented on ProcessMaker/Providers/EventServiceProvider.php
> +        'ProcessMaker\Events\GroupUsersUpdated' => [
Reorder GroupUsersUpdated after GroupDeleted

2023-05-25 18:50 UTC, pmkerberos commented
QA server was successfully deployed https://ci-3895896475.eng.processmaker.net

2023-05-25 19:01 UTC, pmkerberos commented
QA server was successfully deployed https://ci-3895896475.eng.processmaker.net

2023-05-26 15:50 UTC, merged