feature/FOUR-8133
ProcessMaker/processmaker pull request #4793
Opened 2023-05-17 21:12 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
Describe the issue this ticket solves and describe how to reproduce the issue (please attach any fixtures used to reproduce the issue).

## Solution
- List the changes you've introduced to solve the issue.

## How to Test

- Go to admin
- Select edit an user
- Go to groups tab
- Create or Delete a Token
- Check the security_logs table for a new log "tokenCreated" or "tokenDeleted"

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-8233

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy

2023-05-22 17:10 UTC, paulosakamoto commented on ProcessMaker/Events/TokenCreated.php
> +        $this->user = Auth::user();
SecurityLogger already get the session's userid, so `$this->user` is not needed here, as for these events the log record will not be sent to a job queue.

2023-05-22 18:46 UTC, paulosakamoto commented on ProcessMaker/Events/TokenCreated.php
> +    public $user;
Since `$user` is no longer used, could you please remove this line?

2023-05-24 14:35 UTC, paulosakamoto commented on ProcessMaker/Events/TokenCreated.php
> +    public function __construct(Token $created_values)
First, update the branch with the latest feature/FOUR-8121 changes.

Considering the acceptance criteria, would you consider making the following changes?

```php
<?php

namespace ProcessMaker\Events;

use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Auth;
use Laravel\Passport\Token;
use ProcessMaker\Contracts\SecurityLogEventInterface;

class TokenCreated implements SecurityLogEventInterface
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $user;
    public $data;
    public $changes;

    /**
     * Create a new event instance.
     *
     * @param Token $token
     */
    public function __construct(Token $token)
    {
        $this->user = Auth::user();
        $this->data = [
            "Token Id" => $token->getKey()
        ];
        $this->changes = $token->toArray();
    }

    public function getChanges(): array
    {
        return $this->changes;
    }

    public function getData(): array
    {
        return $this->data;
    }

    public function getEventName(): string
    {
        return 'TokenCreated';
    }
}

```

2023-05-24 14:35 UTC, paulosakamoto commented on ProcessMaker/Events/TokenDeleted.php
> +    public function __construct(Token $deleted_values)
Considering the acceptance criteria, would you consider making the following changes?

```php
<?php

namespace ProcessMaker\Events;

use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Auth;
use Laravel\Passport\Token;
use ProcessMaker\Contracts\SecurityLogEventInterface;

class TokenDeleted implements SecurityLogEventInterface
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $user;
    public $data;

    /**
     * Create a new event instance.
     *
     * @param Token $token
     */
    public function __construct(Token $token)
    {
        $this->user = Auth::user();
        $this->data = [
            "Token Id" => $token->getKey()
        ];
    }

    public function getChanges(): array
    {
        return $this->data;
    }

    public function getData(): array
    {
        return $this->data;
    }

    public function getEventName(): string
    {
        return 'TokenDeleted';
    }
}

```

2023-05-24 15:18 UTC, pmkerberos commented
QA server was successfully deployed https://ci-787224fdd3.eng.processmaker.net

2023-05-24 16:01 UTC, pmkerberos commented
QA server was successfully deployed https://ci-787224fdd3.eng.processmaker.net

2023-05-25 15:52 UTC, pmPaulis commented
Please solve the conflicts

2023-05-25 16:33 UTC, pmPaulis requested changes

2023-05-25 16:33 UTC, pmPaulis commented on ProcessMaker/Events/TokenCreated.php
> +    public $data;
Please define the type of data like:
```
private array $data;
private array $changes;
```

2023-05-25 16:33 UTC, pmPaulis commented on ProcessMaker/Events/TokenDeleted.php
> +    public $data;
Please define the type of data like:

```
private array $data;
private array $changes;
```

2023-05-25 16:53 UTC, pmkerberos commented
QA server was successfully deployed https://ci-787224fdd3.eng.processmaker.net

2023-05-25 17:20 UTC, pmPaulis requested changes

2023-05-25 17:20 UTC, pmPaulis commented on ProcessMaker/Events/TokenCreated.php
> +            "Token Id" => $token->getKey()
token_id

2023-05-25 17:20 UTC, pmPaulis commented on ProcessMaker/Events/TokenDeleted.php
> +            "Token Id" => $token->getKey()
token_id

2023-05-25 17:20 UTC, pmkerberos commented
QA server was successfully deployed https://ci-787224fdd3.eng.processmaker.net

2023-05-25 17:44 UTC, pmkerberos commented
QA server was successfully deployed https://ci-787224fdd3.eng.processmaker.net

2023-05-25 18:05 UTC, pmPaulis approved these changes

2023-05-25 18:05 UTC, pmPaulis commented on ProcessMaker/Providers/EventServiceProvider.php
> +        'ProcessMaker\Events\TokenCreated' => [
Move this after SettingsUpdated

2023-05-25 18:06 UTC, merged