Feature/four 8257
ProcessMaker/processmaker pull request #4819
Opened 2023-05-25 17:56 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
N/A
## Solution
N/A
## How to Test
Describe how to test that this solution works.

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-8257

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy

2023-05-25 18:13 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6d8d164da.eng.processmaker.net

2023-05-25 18:21 UTC, pmPaulis requested changes

2023-05-25 18:21 UTC, pmPaulis commented on storage/api-docs/api-docs.json
Please remove those changes

2023-05-25 18:52 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6d8d164da.eng.processmaker.net

2023-05-25 18:52 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6d8d164da.eng.processmaker.net

2023-05-25 19:12 UTC, pmPaulis requested changes

2023-05-25 19:51 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6d8d164da.eng.processmaker.net

2023-05-25 21:02 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6d8d164da.eng.processmaker.net

2023-05-26 14:14 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6d8d164da.eng.processmaker.net

2023-05-26 15:37 UTC, pmPaulis approved these changes

2023-05-26 15:57 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6d8d164da.eng.processmaker.net

2023-05-26 16:29 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6d8d164da.eng.processmaker.net

2023-05-26 16:29 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6d8d164da.eng.processmaker.net

2023-05-26 16:29 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6d8d164da.eng.processmaker.net

2023-05-26 16:29 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6d8d164da.eng.processmaker.net

2023-05-26 18:26 UTC, merged