Feature/four 8242
ProcessMaker/processmaker pull request #4821
Opened 2023-05-25 21:00 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
N/A

## Solution
N/A

## How to Test
Describe how to test that this solution works.

## Related Tickets & Packages
[- Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-8242)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy

2023-05-25 21:16 UTC, pmkerberos commented
QA server was successfully deployed https://ci-e050779d0e.eng.processmaker.net

2023-05-26 13:08 UTC, pmkerberos commented
QA server was successfully deployed https://ci-e050779d0e.eng.processmaker.net

2023-05-26 21:16 UTC, pmkerberos commented
QA server was successfully deployed https://ci-e050779d0e.eng.processmaker.net

2023-05-29 14:48 UTC, pmPaulis requested changes

2023-05-29 19:27 UTC, pmkerberos commented
QA server was successfully deployed https://ci-e050779d0e.eng.processmaker.net

2023-05-30 14:58 UTC, pmPaulis approved these changes

2023-05-30 15:15 UTC, pmkerberos commented
QA server was successfully deployed https://ci-e050779d0e.eng.processmaker.net

2023-05-30 15:15 UTC, pmkerberos commented
QA server was successfully deployed https://ci-e050779d0e.eng.processmaker.net

2023-05-30 15:23 UTC, pmkerberos commented
QA server was successfully deployed https://ci-e050779d0e.eng.processmaker.net

2023-05-31 13:09 UTC, pmPaulis requested changes

2023-05-31 13:09 UTC, pmPaulis commented on ProcessMaker/Events/CustomizeUiUpdated.php
> +    public function __construct(array $original, array $changes, string $update_at)
$update_at please use a lowerCamelCase $updatedAt

2023-05-31 13:34 UTC, pmkerberos commented
QA server was successfully deployed https://ci-e050779d0e.eng.processmaker.net

2023-05-31 14:31 UTC, pmPaulis requested changes

2023-05-31 17:37 UTC, pmPaulis approved these changes

2023-05-31 17:37 UTC, merged