Feature/four 8062
ProcessMaker/processmaker pull request #4869
Opened 2023-06-09 22:18 UTC by gproly

## Issue & Reproduction Steps
Describe the issue this ticket solves and describe how to reproduce the issue (please attach any fixtures used to reproduce the issue).

## Solution
- List the changes you've introduced to solve the issue.

## How to Test
Describe how to test that this solution works.

## Related Tickets & Packages
- Link to any related FOUR tickets, PRDs, or packages

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-06-15 01:12 UTC, nolanpro requested changes

2023-06-15 01:12 UTC, nolanpro commented on ProcessMaker/Notifications/ErrorExecutionNotification.php
> +            $via[] = NotificationChannel::class;
I think this also needs 'broadcast' so it sends the bell icon in real-time. I added some tests you can run that should pass when broadcast is there: tests/Feature/Processes/ErrorExecutionNotificationTest.php

2023-06-15 01:12 UTC, nolanpro commented on ProcessMaker/Notifications/ErrorExecutionNotification.php
> +            ->line($this->message);
Lets customize the email
- The Notification Action should be "View error in app"
- Try adding `->error()`. See https://laravel.com/docs/8.x/notifications#error-messages
- add `->greeting("Request #ID Execution Error")` and `->subject("Request #ID Execution Error")` and replace #ID with the request id

2023-06-20 16:52 UTC, pmkerberos commented
QA server was successfully deployed https://ci-bbddff6bf9.eng.processmaker.net

2023-06-21 19:21 UTC, pmkerberos commented
QA server was successfully deployed https://ci-bbddff6bf9.eng.processmaker.net

2023-06-21 23:45 UTC, pmkerberos commented
QA server was successfully deployed https://ci-bbddff6bf9.eng.processmaker.net

2023-06-21 23:49 UTC, pmkerberos commented
QA server was successfully deployed https://ci-bbddff6bf9.eng.processmaker.net

2023-06-21 23:51 UTC, pmkerberos commented
QA server was successfully deployed https://ci-bbddff6bf9.eng.processmaker.net

2023-06-22 16:25 UTC, pmkerberos commented
QA server was successfully deployed https://ci-bbddff6bf9.eng.processmaker.net

2023-06-23 16:35 UTC, nolanpro approved these changes

2023-06-23 16:35 UTC, merged