FOUR-8235
ProcessMaker/processmaker pull request #4870
Opened 2023-06-12 20:11 UTC by pmPaulis

## Issue & Reproduction Steps
Register some events related to user activity events according to the [PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3084320783/User+Activity+Logging).
Related to the Log Access to any files -> File manager

## Solution
- Improve the tickets definition

## How to Test
Needs to make the following actions:
- Create Files / Folder
- Update Files / Folder

## Related Tickets & Packages
- [FOUR-8235](https://processmaker.atlassian.net/browse/FOUR-8235)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.
## enviroment
ci:deploy
ci:processmaker:feature/FOUR-8235

2023-06-13 13:52 UTC, pmkerberos commented
QA server was successfully deployed https://ci-29271c41e3.eng.processmaker.net

2023-06-14 14:40 UTC, pmkerberos commented
QA server was successfully deployed https://ci-29271c41e3.eng.processmaker.net

2023-06-14 14:40 UTC, pmkerberos commented
QA server was successfully deployed https://ci-29271c41e3.eng.processmaker.net

2023-06-14 19:38 UTC, fagubla requested changes

2023-06-14 19:38 UTC, fagubla commented on ProcessMaker/Events/FilesCreated.php
> +            'name' => [
change **name** by **file_name**

2023-06-14 19:38 UTC, fagubla commented on ProcessMaker/Events/FilesDeleted.php
> +            'name' => $this->fileName,
same as about

2023-06-15 14:39 UTC, pmkerberos commented
QA server was successfully deployed https://ci-29271c41e3.eng.processmaker.net

2023-06-15 14:53 UTC, fagubla approved these changes

2023-06-15 15:06 UTC, pmkerberos commented
QA server was successfully deployed https://ci-29271c41e3.eng.processmaker.net

2023-06-15 15:06 UTC, pmkerberos commented
QA server was successfully deployed https://ci-29271c41e3.eng.processmaker.net

2023-06-15 15:06 UTC, pmkerberos commented
QA server was successfully deployed https://ci-29271c41e3.eng.processmaker.net

2023-06-15 15:06 UTC, pmkerberos commented
QA server was successfully deployed https://ci-29271c41e3.eng.processmaker.net

2023-06-15 15:06 UTC, pmkerberos commented
QA server was successfully deployed https://ci-29271c41e3.eng.processmaker.net

2023-06-15 18:16 UTC, pmkerberos commented
QA server was successfully deployed https://ci-29271c41e3.eng.processmaker.net

2023-06-15 22:23 UTC, merged