Feature/four 8901
ProcessMaker/processmaker pull request #4878
Opened 2023-06-14 18:39 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
N/A

## Solution
N/A

## How to Test
N/A

## Related Tickets & Packages
[- Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-8901)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

## Enviroment
ci:deploy

2023-06-14 18:53 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-14 18:59 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-14 19:56 UTC, fagubla requested changes

2023-06-14 19:56 UTC, fagubla commented on ProcessMaker/Http/Controllers/Api/CssOverrideController.php
> +            $original['config'] = array_merge(isset($footer['original']) ? $footer['original'] : [], isset($altText['original']) ? $altText['original'] : [], isset($original['config']) ? $original['c
This line is too long, could you split in multiple lines?

2023-06-14 19:56 UTC, fagubla commented on ProcessMaker/Http/Controllers/Api/CssOverrideController.php
> +        $changes = array_merge(isset($footer['changes']) ? $footer['changes'] : [], isset($altText['changes']) ? $altText['changes'] : [], $changes);
This line is too long, could you split in multiple lines?

2023-06-14 20:29 UTC, fagubla approved these changes

2023-06-15 11:58 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-15 11:58 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-15 11:58 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-15 11:59 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-15 11:59 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-15 13:39 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-15 13:54 UTC, pmPaulis requested changes

2023-06-15 13:54 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/CssOverrideController.php
> +                isset($footer['original']) ? $footer['original'] : [],
Please use the shorthand comparison:
`$footer['original'] ?? [],`

2023-06-15 14:19 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-15 15:24 UTC, pmPaulis requested changes

2023-06-15 15:24 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/CssOverrideController.php
> +                'original' => ['loginFooter' => isset($original) ? $original : '']
Please use this:
`'original' => ['loginFooter' => $original ?? '']`

2023-06-15 15:42 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-15 15:48 UTC, pmPaulis approved these changes

2023-06-15 16:03 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-15 19:25 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-16 18:44 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-16 18:44 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-16 18:44 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-16 18:51 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-16 20:16 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-19 14:39 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-06-19 22:44 UTC, pmPaulis requested changes

2023-06-19 22:44 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/CssOverrideController.php
> +        $original = isset($original) ? $original->getAttribute('config')['html'] : '';
Please validate if ['html'] exist

2023-06-19 22:44 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/CssOverrideController.php
> +                'changes' => ['loginFooter' => $setting->getAttributes()['config']['html']],
Please validate if ['html'] exist the use
$setting->getAttribute('config') insteand of $setting->getAttributes()['config']

2023-06-19 23:16 UTC, pmkerberos commented
QA server was successfully deployed https://ci-a6841ab6d4.eng.processmaker.net

2023-07-20 17:33 UTC, closed without merging