Feature/four 8264
ProcessMaker/processmaker pull request #4888
Opened 2023-06-16 14:50 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
Create, Cancelled or Completed a Request

## Solution

## How to Test
- Create a Request
- Go to admin an edit user
- Select tab security logs
- The same when you delete an complete a Request

## Related Tickets & Packages
[- Link to any related FOUR tickets, PRDs, or packages
](https://processmaker.atlassian.net/browse/FOUR-8264)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

## Enviroment
ci:deploy

2023-06-16 15:06 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b0d031d831.eng.processmaker.net

2023-06-16 15:10 UTC, fagubla requested changes

2023-06-16 15:10 UTC, fagubla commented on ProcessMaker/Events/RequestAction.php
> +        switch ($this->action) {
Instead use switch, use `array_search`

2023-06-16 15:10 UTC, fagubla commented on ProcessMaker/Http/Controllers/Api/ProcessController.php
> +        event(new RequestAction($processRequest, RequestAction::ACTIONS[0]));
Hardcode 0, send the label

2023-06-16 15:10 UTC, fagubla commented on ProcessMaker/Observers/ProcessRequestObserver.php
> +        event(new RequestAction($request, RequestAction::ACTIONS[2]));
use the correct indentation

2023-06-16 15:12 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b0d031d831.eng.processmaker.net

2023-06-16 16:14 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b0d031d831.eng.processmaker.net

2023-06-16 16:26 UTC, fagubla requested changes

2023-06-16 16:26 UTC, fagubla commented on ProcessMaker/Events/RequestAction.php
> +    const ACTION_CANCELLED = 'CANCELLED';
misspelled put **CANCELED**

2023-06-16 16:27 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b0d031d831.eng.processmaker.net

2023-06-16 16:33 UTC, fagubla approved these changes

2023-06-16 16:40 UTC, pmPaulis requested changes

2023-06-16 16:40 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/ProcessController.php
> +        event(new RequestAction($processRequest, 'CREATED'));
event(new RequestAction($processRequest, RequestAction::ACTION_CREATED));

2023-06-16 16:41 UTC, pmPaulis requested changes

2023-06-16 16:41 UTC, pmPaulis commented on ProcessMaker/Events/RequestAction.php
> +    const ACTION_CANCELED = 'CANCELED';
alphabetical order

2023-06-16 16:48 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b0d031d831.eng.processmaker.net

2023-06-16 19:26 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b0d031d831.eng.processmaker.net

2023-06-17 00:12 UTC, pmPaulis approved these changes

2023-06-17 00:24 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b0d031d831.eng.processmaker.net

2023-06-20 19:28 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b0d031d831.eng.processmaker.net

2023-06-20 19:35 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b0d031d831.eng.processmaker.net

2023-06-20 19:47 UTC, merged