FOUR-8972
ProcessMaker/processmaker pull request #4889
Opened 2023-06-16 15:19 UTC by pmPaulis

## Issue & Reproduction Steps
Register some events related to user activity events according to the [PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3084320783/User+Activity+Logging).
Make some changes related to label and getChanges

## Solution
- Improve the tickets definition

## How to Test
Check the actions related to 
     - CategoryCreated.php
        - CategoryUpdated.php
        - CustomizeUiUpdated.php
        - EnvironmentVariablesCreated.php
        - EnvironmentVariablesDeleted.php
        - EnvironmentVariablesUpdated.php
        - FilesUpdated.php
        - GroupCreated.php
        - ProcessArchived.php
        - ProcessCreated.php
        - ProcessPublished.php
        - ProcessRestored.php
        - ScreenCreated.php
        - ScreenDeleted.php
        - ScriptCreated.php
        - ScriptDeleted.php
        - ScriptExecutorCreated.php
        - ScriptExecutorDeleted.php
        - ScriptExecutorUpdated.php
        - ScriptUpdated.php
        - SettingsUpdated.php
        - TemplateCreated.php
        - TemplateUpdated.php
        - TokenCreated.php
        - TokenDeleted.php

## Related Tickets & Packages
[FOUR-8972](https://processmaker.atlassian.net/browse/FOUR-8972)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

## Enviroment
ci:deploy

2023-06-16 15:35 UTC, fagubla requested changes

2023-06-16 15:35 UTC, fagubla commented on ProcessMaker/Events/EnvironmentVariablesCreated.php
> +                'label' => $this->variable['name'] ?? '',
This label must not be empty, because the modal will not display the link

2023-06-16 15:36 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b1d9f0e151.eng.processmaker.net

2023-06-16 15:36 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b1d9f0e151.eng.processmaker.net

2023-06-16 17:39 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b1d9f0e151.eng.processmaker.net

2023-06-16 18:29 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b1d9f0e151.eng.processmaker.net

2023-06-16 18:29 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b1d9f0e151.eng.processmaker.net

2023-06-16 18:29 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b1d9f0e151.eng.processmaker.net

2023-06-16 18:29 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b1d9f0e151.eng.processmaker.net

2023-06-16 18:29 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b1d9f0e151.eng.processmaker.net

2023-06-17 00:05 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b1d9f0e151.eng.processmaker.net

2023-06-19 14:01 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b1d9f0e151.eng.processmaker.net

2023-06-19 15:05 UTC, pmkerberos commented
QA server was successfully deployed https://ci-b1d9f0e151.eng.processmaker.net

2023-06-19 23:26 UTC, merged