feature/FOUR-8243
ProcessMaker/processmaker pull request #4907
Opened 2023-06-20 17:29 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
log a Request error

## How to Test
- Create a Request with an error
- Run the request

## Related Tickets & Packages
[- Link to any related FOUR tickets, PRDs, or packages
](https://processmaker.atlassian.net/browse/FOUR-8243)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

## Enviroment
ci:deploy

2023-06-20 17:42 UTC, fagubla requested changes

2023-06-20 17:42 UTC, fagubla commented on ProcessMaker/Events/RequestError.php
> +        $parentProcess = Process::find($this->data->getAttribute('process_id'));
delete this variable is not being used

2023-06-20 17:50 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-20 17:50 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-20 17:57 UTC, fagubla approved these changes

2023-06-20 18:02 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-20 18:10 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-20 18:10 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-20 18:10 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-20 18:10 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-20 18:10 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-20 18:10 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-20 19:07 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-20 20:35 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-20 20:45 UTC, pmPaulis approved these changes

2023-06-22 15:14 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-22 15:53 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-22 16:28 UTC, caleeli commented on ProcessMaker/Models/ProcessRequest.php
>          \Log::error($exception);
If this `\Log::error()` is not required or was used for debugging, please remove it.

2023-06-22 17:28 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-22 17:47 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-22 18:08 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-23 16:45 UTC, pmPaulis approved these changes

2023-06-23 17:27 UTC, pmkerberos commented
QA server was successfully deployed https://ci-8d49dc98ff.eng.processmaker.net

2023-06-23 17:37 UTC, pmPaulis approved these changes

2023-06-23 18:26 UTC, merged