FOUR-8720: Add S3 Download
ProcessMaker/processmaker pull request #4928
Opened 2023-06-26 19:57 UTC by pmPaulis

## Issue & Reproduction Steps
Describe the issue this ticket solves and describe how to reproduce the issue (please attach any fixtures used to reproduce the issue).

## Solution
- List the changes you've introduced to solve the issue.

## How to Test
Describe how to test that this solution works.

## Related Tickets & Packages
- Link to any related FOUR tickets, PRDs, or packages

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-06-26 20:14 UTC, pmkerberos commented
QA server was successfully deployed https://ci-d12b9fb33a.eng.processmaker.net

2023-06-26 20:14 UTC, pmkerberos commented
QA server was successfully deployed https://ci-d12b9fb33a.eng.processmaker.net

2023-06-27 20:32 UTC, pmkerberos commented
QA server was successfully deployed https://ci-d12b9fb33a.eng.processmaker.net

2023-06-27 20:56 UTC, pmkerberos commented
QA server was successfully deployed https://ci-d12b9fb33a.eng.processmaker.net

2023-06-27 21:13 UTC, caleeli commented on tests/Feature/Jobs/DownloadSecurityLogTest.php
> +        $this->expectsEvents(SecurityLogDownloadJobCompleted::class);
Seems this code is never reached.

2023-06-27 21:13 UTC, caleeli commented on tests/Feature/Jobs/DownloadSecurityLogTest.php
> +        $this->expectsEvents(SecurityLogDownloadJobCompleted::class);
Seems this code is never reached.

2023-06-27 21:43 UTC, pmkerberos commented
QA server was successfully deployed https://ci-d12b9fb33a.eng.processmaker.net

2023-06-27 22:11 UTC, pmkerberos commented
QA server was successfully deployed https://ci-d12b9fb33a.eng.processmaker.net

2023-06-28 12:33 UTC, fagubla requested changes

2023-06-28 12:33 UTC, fagubla commented on ProcessMaker/Jobs/DownloadSecurityLog.php
> +        return now()->addHours(24);
hardcode 24

2023-06-28 12:41 UTC, fagubla approved these changes

2023-06-28 14:02 UTC, caleeli approved these changes

2023-06-29 13:31 UTC, merged