FOUR-9704
ProcessMaker/processmaker pull request #5076
Opened 2023-08-01 20:07 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
Some information needs correction

## How to Test

1. Review the following events:
  a. Publish a Template
  b. Update a script
  c. Create a Decision Category
9. Check the User Activity Logging 

## Related Tickets & Packages
[- Link to any related FOUR tickets, PRDs, or package](https://processmaker.atlassian.net/browse/FOUR-9704)s

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-08-01 20:56 UTC, fagubla approved these changes

2023-08-02 15:41 UTC, pmPaulis requested changes

2023-08-02 15:41 UTC, pmPaulis commented on resources/lang/en.json
> +  "Script_category": "Script Category",
Only "Category" Please intead of "Script Category"

2023-08-04 18:34 UTC, pmPaulis approved these changes

2023-08-08 21:27 UTC, merged