feature/FOUR-9580: Add the Next and Previous Buttons
ProcessMaker/processmaker pull request #5120
Opened 2023-08-09 19:16 UTC by luNunezProcessmaker

## Issue & Reproduction Steps

Add the Next and Previous Buttons

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-9580

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy

2023-08-10 11:47 UTC, fagubla requested changes

2023-08-10 11:47 UTC, fagubla commented on resources/js/tasks/components/TasksPreview.vue
create a new component for these buttons

2023-08-10 20:39 UTC, tokensPM commented
QA server was successfully deployed https://ci-277fbf085c.eng.processmaker.net

2023-08-11 13:47 UTC, fagubla approved these changes

2023-08-11 13:47 UTC, merged