Feature/four 9924 data tree visualization on the data connector
ProcessMaker/processmaker pull request #5200
Opened 2023-08-24 15:27 UTC by gustavobascope

## Issue & Reproduction Steps
Data Connectors - Add to Response Body tab

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-9924

ci:deploy

2023-08-24 15:48 UTC, tokensPM commented
QA server was successfully deployed https://ci-8c859fadfe.eng.processmaker.net

2023-08-24 18:19 UTC, nolanpro requested changes

2023-08-24 18:19 UTC, nolanpro commented on resources/js/bootstrap.js
> +import TreeView from "./components/TreeView.vue";
@gustavobascope If we are going to include this globally can we remove it from resources/js/requests/show.js and resources/js/tasks/show.js ?

2023-08-24 18:45 UTC, tokensPM commented
QA server was successfully deployed https://ci-8c859fadfe.eng.processmaker.net

2023-08-24 19:07 UTC, tokensPM commented
QA server was successfully deployed https://ci-8c859fadfe.eng.processmaker.net

2023-08-24 21:56 UTC, tokensPM commented
QA server was successfully deployed https://ci-8c859fadfe.eng.processmaker.net

2023-08-25 17:32 UTC, nolanpro approved these changes

2023-08-25 17:32 UTC, merged