Feature/four 10112  data tree visualization in the script editor
ProcessMaker/processmaker pull request #5256
Opened 2023-09-05 16:09 UTC by gustavobascope

## Issue & Reproduction Steps
 data tree visualization in the script editor

## Solution
We added a expand button to show the JSON Browser in the screen of the script editor

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-10112

ci:next

2023-09-06 15:38 UTC, gproly approved these changes

2023-09-11 22:46 UTC, nolanpro requested changes

2023-09-12 19:29 UTC, gustavobascope commented
The changes were made

2023-09-12 22:27 UTC, nolanpro approved these changes
Looks good thanks

2023-09-12 22:27 UTC, merged