feature/FOUR-9622: Add a default dropdown to define the SSO login
ProcessMaker/processmaker pull request #5261
Opened 2023-09-05 21:28 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
![Fall-23-–-Figma (7)](https://github.com/ProcessMaker/processmaker/assets/123644082/2aa2a62b-ed31-45c1-933a-f96b3a2a5e22)
![Fall-23-–-Figma (8)](https://github.com/ProcessMaker/processmaker/assets/123644082/c0b07716-4e4f-4b4c-9c1c-246789da0d3a)

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-9622

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next

2023-09-06 13:42 UTC, fagubla commented on resources/js/admin/settings/components/SettingsListing.vue
> +            <span v-if="row.item.key !== 'sso.default.login'" >
use template tag instead of span tag

2023-09-06 13:44 UTC, pmPaulis requested changes

2023-09-06 13:44 UTC, pmPaulis commented on database/migrations/2023_09_05_154257_add_sso_field_in_settings_table.php
> +use PhpParser\Node\Stmt\Foreach_;
Remove this line u`se PhpParser\Node\Stmt\Foreach_;`

2023-09-06 13:44 UTC, pmPaulis commented on database/migrations/2023_09_05_154257_add_sso_field_in_settings_table.php
> +return new class extends Migration {
Update to 
`class AddSsoFieldInSettingsTable extends Migration`

2023-09-06 13:44 UTC, pmPaulis commented on database/migrations/2023_09_05_154257_add_sso_field_in_settings_table.php
The information about this need property needs to be added in the **package-auth**
`php artisan make:seeder AuthDeafaultSeeder`

2023-09-06 13:44 UTC, pmPaulis commented on database/migrations/2023_09_05_154257_add_sso_field_in_settings_table.php
> +        $elements = Setting::where('key', 'LIKE', 'services%')->where('group', 'LIKE', 'SSO')->get()->toArray();
Use a where equal not Like

2023-09-06 13:54 UTC, fagubla commented on resources/js/admin/settings/components/SettingsListing.vue
> +                  <i class="fa-lg fas fa-copy"></i>
If the tag doesn't have any value must be closed in the same.
in this case:
<i class="fa-lg fas fa-copy" />

2023-09-06 13:56 UTC, fagubla commented on resources/js/admin/settings/components/SettingsListing.vue
> +                :aria-label="$t('Clear')"
Use a correct indentation.
Order the attributes as I mentioned about

2023-09-06 13:57 UTC, fagubla commented on resources/js/admin/settings/components/SettingsListing.vue
> +                  <i class="fa-lg fas fa-trash-alt"></i>
same here

2023-09-06 13:57 UTC, fagubla commented on resources/js/admin/settings/components/SettingsListing.vue
> +                  v-uni-aria-describedby="row.item.id.toString()">
> in a new line

2023-09-06 13:57 UTC, fagubla commented on resources/js/admin/settings/components/SettingsListing.vue
> +                    <i class="fas fa-trash-alt"></i>
same here

2023-09-07 12:51 UTC, fagubla requested changes

2023-09-07 12:51 UTC, fagubla commented on resources/js/admin/settings/components/SettingsListing.vue
> +                variant="link"
this attribute must be go before :aria-label

2023-09-07 12:51 UTC, fagubla commented on resources/js/admin/settings/components/SettingsListing.vue
> +                  variant="link"
same here

2023-09-07 17:54 UTC, merged