FOUR-10447: Add Preview for screens
ProcessMaker/processmaker pull request #5325
Opened 2023-09-15 14:35 UTC by danloa

## Issue & Reproduction Steps
Adds the Preview for Screens. This preview will be used in modeler.

![image](https://github.com/ProcessMaker/processmaker/assets/14875032/302e115e-2e04-4355-a999-5b973982d9a2)

## Related Tickets & Packages
- [https://processmaker.atlassian.net/browse/FOUR-10447](https://processmaker.atlassian.net/browse/FOUR-10447)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-09-15 17:42 UTC, tokensPM commented
QA server was successfully deployed https://ci-757dfb090c.eng.processmaker.net

2023-09-15 18:20 UTC, tokensPM commented
QA server was successfully deployed https://ci-757dfb090c.eng.processmaker.net

2023-09-18 20:37 UTC, josechirivella requested changes

2023-09-18 20:37 UTC, josechirivella commented on resources/js/processes/modeler/initialLoad.js
> +    evento.registerPreview({
```suggestion
  (event) => {
    event.registerPreview({
```

2023-09-18 20:37 UTC, josechirivella commented on resources/js/processes/modeler/initialLoad.js
> +        return nodeData.$type && nodeData.$type === 'bpmn:Task'
try to see if this is compiled
```suggestion
        return nodeData?.$type === 'bpmn:Task'
```

2023-09-21 15:49 UTC, tokensPM commented
QA server was successfully deployed https://ci-757dfb090c.eng.processmaker.net

2023-09-21 22:35 UTC, josechirivella requested changes

2023-09-21 22:35 UTC, josechirivella commented on resources/js/processes/scripts/components/ScriptPreview.vue
> +        }
I dont think this is necessary? 
```suggestion
  console.error(err)
```

2023-09-21 22:35 UTC, josechirivella commented on resources/js/processes/scripts/components/ScriptPreview.vue
> +    stopResizing: _.debounce(function() {
```suggestion
    stopResizing: debounce(function() {
```

2023-09-21 22:35 UTC, josechirivella commented on resources/js/processes/scripts/components/ScriptPreview.vue
> +import _ from "lodash";
```suggestion
import { debounce } from "lodash";
```

2023-10-04 20:05 UTC, tokensPM commented
QA server was successfully deployed https://ci-757dfb090c.eng.processmaker.net

2023-10-04 20:33 UTC, tokensPM commented
QA server was successfully deployed https://ci-757dfb090c.eng.processmaker.net

2023-10-04 22:58 UTC, josechirivella approved these changes

2023-10-06 21:01 UTC, merged