Feature/four 9496: Designer: Show the Projects
ProcessMaker/processmaker pull request #5411
Opened 2023-10-03 17:25 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
As a Designer I want to have a quick access to Recently Opened Projects.
![image-20231002-153100](https://github.com/ProcessMaker/processmaker/assets/123644082/bf1014f3-b1dc-46e7-bae4-fbe6a47aa76a)

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-9496

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next

2023-10-03 18:31 UTC, tokensPM commented
QA server was successfully deployed https://ci-7efc34d7db.eng.processmaker.net

2023-10-03 18:58 UTC, tokensPM commented
QA server was successfully deployed https://ci-7efc34d7db.eng.processmaker.net

2023-10-03 19:39 UTC, fagubla requested changes

2023-10-03 19:39 UTC, fagubla commented on resources/js/processes/designer/MyProject.vue
> +    <div v-if="false" class="container">
why???

2023-10-03 19:39 UTC, fagubla commented on resources/js/processes/designer/ProcessesLastModifiedListing.vue
> +      :for="/\/processes\?page/"
this is not closed correctly

2023-10-03 19:39 UTC, fagubla commented on resources/js/processes/designer/ProcessesLastModifiedListing.vue
> +          <a v-bind:href="`/designer/projects/${props.rowData.id}`" v-uni-id="props.rowData.id.toString()">{{props.rowData.title}}
the value must go in a new line

2023-10-03 19:41 UTC, fagubla requested changes

2023-10-03 19:41 UTC, fagubla commented on resources/js/processes/designer/ProcessesLastModifiedListing.vue
> +  <div v-if="!existData" class="container">
What happen if existData is an empty array ?

2023-10-03 20:34 UTC, tokensPM commented
QA server was successfully deployed https://ci-7efc34d7db.eng.processmaker.net

2023-10-04 11:54 UTC, fagubla requested changes

2023-10-04 11:54 UTC, fagubla commented on resources/js/processes/designer/ProcessesLastModifiedListing.vue
> +  <div v-if="!data" class="container">
data.length === 0

2023-10-04 11:54 UTC, fagubla commented on resources/js/processes/designer/ProcessesLastModifiedListing.vue
> +        { value: "open-item", content: "Open", link: true, href: "/designer/projects/{{id}}", icon: "fas fa-sign-in-alt"},
fix the code style like fields

2023-10-04 11:54 UTC, fagubla commented on resources/js/processes/designer/ProcessesLastModifiedListing.vue
> +  props: ["status", "permission", "isDocumenterInstalled", "currentUserId"],
what is the purpose of these props?

2023-10-04 13:03 UTC, fagubla approved these changes

2023-10-04 13:33 UTC, tokensPM commented
QA server was successfully deployed https://ci-7efc34d7db.eng.processmaker.net

2023-10-04 15:42 UTC, tokensPM commented
QA server was successfully deployed https://ci-7efc34d7db.eng.processmaker.net

2023-10-04 15:53 UTC, merged