QA Observation: Bugfix/FOUR-12502 The fields are not cleared after closing the modal
ProcessMaker/processmaker pull request #5680
Opened 2023-11-21 19:38 UTC by CarliPinell

## Solution
- Modal window clear all fields on Close

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.
ci:deploy

2023-11-21 19:55 UTC, tokensPM commented
QA server was successfully deployed https://ci-836ac54264.eng.processmaker.net

2023-11-22 13:37 UTC, fagubla requested changes

2023-11-22 13:47 UTC, ana-mauricio requested changes
En esta parte la seleccion de usuario est oculta. SI se cambia el usuario por otro este se queda por defecto y los siguientes scripts seran creados con ese usuario.

El campo user, no se limpia despues que el modal se cierra como se muestra en el video:

https://github.com/ProcessMaker/processmaker/assets/21198450/a693f54a-14c8-4ae9-9f25-a66e647aeee1

@fagubla @pmPaulis

2023-11-22 14:25 UTC, CarliPinell commented on resources/js/processes/scripts/components/CreateScriptModal.vue
> +      @hidden="modalHidden"
Solved

2023-11-22 14:39 UTC, tokensPM commented
QA server was successfully deployed https://ci-836ac54264.eng.processmaker.net

2023-11-22 15:08 UTC, ana-mauricio approved these changes

2023-11-22 15:20 UTC, fagubla approved these changes

2023-11-22 17:00 UTC, merged