FOUR-11415 Password Policy Configuration
ProcessMaker/processmaker pull request #5682
Opened 2023-11-22 14:15 UTC by julceslauhub

## Issue & Reproduction Steps
The passwords policies are not configurable

## Solution
Added validations when the users login to the app

## How to Test
Add in .env the next values:
`PASSWORD_POLICY_NUMBERS=TRUE
PASSWORD_POLICY_UPPERCASE=TRUE
PASSWORD_POLICY_SPECIAL=TRUE
PASSWORD_POLICY_MINIMUM_LENGTH=8
PASSWORD_POLICY_MAXIMUM_LENGTH=12
PASSWORD_POLICY_LOGIN_ATTEMPTS=5`

And validate when user login to the app

## Related Tickets & Packages
- Link to any related FOUR tickets, PRDs, or packages
https://processmaker.atlassian.net/browse/FOUR-11415

## Code Review Checklist
- [x] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [x] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [x] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [x] This solution fixes the bug reported in the original ticket.
- [x] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [x] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [x] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [x] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [x] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-11-23 20:50 UTC, caleeli commented on resources/views/shared/users/sidebar.blade.php
> +                <div class="invalid-feedback" :style="{display: (errors.password) ? 'block' : 'none' }" role="alert" v-for="(error, index) in errors.password">@{{error}}</div>
Please split thi line in multiple lines to enhance readability

2023-11-23 21:57 UTC, caleeli requested changes
@julceslauhub review or update the password related tests, so they pass accordingly to the new password policy

![image](https://github.com/ProcessMaker/processmaker/assets/8028650/2334d3ed-b40c-4602-b788-7a26bee16fde)

2023-11-24 16:03 UTC, caleeli approved these changes

2023-11-24 21:40 UTC, boliviacoca approved these changes

2023-11-27 13:06 UTC, merged