Standard Login option doesn't work in SSO configuration
ProcessMaker/processmaker pull request #5694
Opened 2023-11-23 17:24 UTC by marcoAntonioNina

## Issue & Reproduction Steps
When there is a problem in the SSO configuration, it does not allow you to log in

## Solution
- Add variable Error SSO

## How to Test
Configure SSO login with correct and incorrect configuration
login

## Related Tickets & Packages
- [FOUR-12542](https://processmaker.atlassian.net/browse/FOUR-12542)

Depends
https://github.com/ProcessMaker/package-auth/pull/92

ci:package-auth:bugfix/FOUR-12542
ci:deploy

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2023-11-23 19:07 UTC, pmPaulis approved these changes

2023-11-23 19:08 UTC, pmPaulis commented
When the URL for default login is broken it will redirect to normal login like:
![image](https://github.com/ProcessMaker/processmaker/assets/42388723/c5895259-1eec-4efd-9677-bb82c71d0764)

2023-11-23 19:43 UTC, pmPaulis requested changes
Marquiño, please review Default login with google

2023-11-23 23:40 UTC, tokensPM commented
QA server was successfully deployed https://ci-285f41756a.eng.processmaker.net

2023-11-24 18:53 UTC, marcoAntonioNina commented
The changes do not apply

2023-11-24 18:53 UTC, closed without merging