Feature/four 11536
ProcessMaker/processmaker pull request #5714
Opened 2023-11-29 16:45 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
As a user, I want a button to kick off, for each start event so it is easier for me to access.

Please consider the look and fill when the processes has more than one Start event

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-11536

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

2023-11-29 17:11 UTC, tokensPM commented
QA server was successfully deployed https://ci-ec57c92e8a.eng.processmaker.net

2023-11-29 17:11 UTC, fagubla requested changes

2023-11-29 17:11 UTC, fagubla commented on resources/js/processes-catalogue/components/ProcessOptions.vue
> +    getStartEvents() {
documentation is missing

2023-11-29 17:11 UTC, fagubla commented on resources/js/processes-catalogue/components/ProcessOptions.vue
> +    goToNewRequest(event) {
documentation is missing,
perhaps this method could become a helper or mixin, since the same logic is being used in several sections.

2023-11-29 17:11 UTC, fagubla commented on resources/js/processes-catalogue/components/ProcessOptions.vue
> +      window.ProcessMaker.apiClient
window is not necessary

2023-11-29 17:11 UTC, fagubla commented on resources/js/processes-catalogue/components/ProcessOptions.vue
> +      window.ProcessMaker.apiClient
window is not necessary

2023-11-29 17:11 UTC, fagubla commented on resources/js/processes-catalogue/components/ProcessOptions.vue
> +          if (this.$cookies.get("isMobile") === "true") {
verify if is mobile is not necessary, launchpad only will run in desktop

2023-11-29 17:53 UTC, tokensPM commented
QA server was successfully deployed https://ci-ec57c92e8a.eng.processmaker.net

2023-11-29 19:26 UTC, fagubla approved these changes

2023-11-29 19:27 UTC, tokensPM commented
QA server was successfully deployed https://ci-ec57c92e8a.eng.processmaker.net

2023-11-29 20:22 UTC, tokensPM commented
QA server was successfully deployed https://ci-ec57c92e8a.eng.processmaker.net

2023-11-30 12:41 UTC, merged

2023-11-30 13:07 UTC, tokensPM commented
QA server was successfully deployed https://ci-ec57c92e8a.eng.processmaker.net