FOUR-12709: FOUR-11533: Add Metric "Request of process"
ProcessMaker/processmaker pull request #5841
Opened 2023-12-18 19:36 UTC by pmPaulis

## Issue & Reproduction Steps
FOUR-11533: Add Metric "Request of process"

## Solution
- List the changes you've introduced to solve the issue.

## How to Test
Describe how to test that this solution works.

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-12709

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.
ci:deploy
ci:next

2023-12-18 20:03 UTC, tokensPM commented
QA server was successfully deployed https://ci-1744f930eb.eng.processmaker.net

2023-12-18 20:26 UTC, tokensPM commented
QA server was successfully deployed https://ci-1744f930eb.eng.processmaker.net

2023-12-19 14:07 UTC, tokensPM commented
QA server was successfully deployed https://ci-1744f930eb.eng.processmaker.net

2023-12-19 14:49 UTC, fagubla requested changes

2023-12-19 14:49 UTC, fagubla commented on resources/js/processes-catalogue/components/optionsMenu/ProcessCounter.vue
> +  font-family: "Open Sans", sans-serif;
remove this line
this font is by default in all PM4

2023-12-19 14:49 UTC, fagubla commented on resources/js/processes-catalogue/components/optionsMenu/ProcessCounter.vue
> +  font-family: "Open Sans", sans-serif;
remove this line
this font is by default in all PM4

2023-12-19 15:18 UTC, fagubla approved these changes

2023-12-19 15:30 UTC, tokensPM commented
QA server was successfully deployed https://ci-1744f930eb.eng.processmaker.net

2023-12-19 16:19 UTC, merged