FOUR-12992: The permission View Process Catalog, needs to enable per Default for the new users
ProcessMaker/processmaker pull request #5859
Opened 2023-12-20 19:17 UTC by pmPaulis

## Issue & Reproduction Steps
The permission View Process Catalog, needs to enable per Default for the new users

## How to Test
Describe how to test that this solution works.

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-12992

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

2023-12-20 19:38 UTC, tokensPM commented
QA server was successfully deployed https://ci-1ace39794f.eng.processmaker.net

2023-12-20 20:07 UTC, tokensPM commented
QA server was successfully deployed https://ci-1ace39794f.eng.processmaker.net

2023-12-20 20:56 UTC, tokensPM commented
QA server was successfully deployed https://ci-1ace39794f.eng.processmaker.net

2023-12-20 22:10 UTC, caleeli requested changes

2023-12-20 22:10 UTC, caleeli commented on ProcessMaker/Observers/UserObserver.php
> +        $permission = Permission::byName('view-process-catalog')->first();
Consider to add an upgrade to create the new permission `view-process-catalog`

The code seem to fail, when you send a string the function returns the Permission object and you do not need to call the method `first()`:

```suggestion
        $permission = Permission::byName('view-process-catalog')
```

2023-12-21 14:52 UTC, tokensPM commented
QA server was successfully deployed https://ci-1ace39794f.eng.processmaker.net

2023-12-21 16:13 UTC, tokensPM commented
QA server was successfully deployed https://ci-1ace39794f.eng.processmaker.net

2023-12-21 17:18 UTC, tokensPM commented
QA server was successfully deployed https://ci-1ace39794f.eng.processmaker.net

2023-12-21 18:53 UTC, tokensPM commented
QA server was successfully deployed https://ci-1ace39794f.eng.processmaker.net

2023-12-21 19:09 UTC, pmPaulis commented
@caleeli 
I reviewed the functionality, please see the video

https://github.com/ProcessMaker/processmaker/assets/42388723/ac284e87-0746-4650-a1d3-f43e54c46a95

2023-12-21 19:34 UTC, tokensPM commented
QA server was successfully deployed https://ci-1ace39794f.eng.processmaker.net

2023-12-21 22:39 UTC, tokensPM commented
QA server was successfully deployed https://ci-1ace39794f.eng.processmaker.net

2023-12-21 22:54 UTC, caleeli commented on upgrades/2023_12_21_142322_create_permission_view_process_catalog.php
> +        if (!Permission::where('name', 'view-process-catalog')->first()) {
Consider to use:
```
Permission::updateOrCreate(...)
```

2023-12-21 22:55 UTC, caleeli commented on upgrades/2023_12_21_142322_create_permission_view_process_catalog.php
> +        if ($permission = Permission::where('name', 'view-process-catalog')->first()) {
Consider to use:
```
Permission::where('name', 'view-process-catalog')->delete();
```

2023-12-21 23:06 UTC, caleeli approved these changes

2023-12-21 23:19 UTC, tokensPM commented
QA server was successfully deployed https://ci-1ace39794f.eng.processmaker.net

2023-12-22 12:00 UTC, tokensPM commented
QA server was successfully deployed https://ci-1ace39794f.eng.processmaker.net

2023-12-22 12:49 UTC, tokensPM commented
QA server was successfully deployed https://ci-1ace39794f.eng.processmaker.net

2023-12-22 14:23 UTC, tokensPM commented
QA server was successfully deployed https://ci-1ace39794f.eng.processmaker.net

2023-12-22 14:29 UTC, merged