FOUR-11538-C: Process Launchpad - Tabs: My requests - My Task
ProcessMaker/processmaker pull request #5894
Opened 2024-01-02 15:54 UTC by CarliPinell

## How to Test
-  Open Any Process with "Open in Launchpad" and check

## Related Tickets & Packages
- Link to any related FOUR tickets, PRDs, or packages

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.
ci:deploy
ci:next

2024-01-02 16:16 UTC, tokensPM commented
QA server was successfully deployed https://ci-7ff8c20262.eng.processmaker.net

2024-01-02 17:01 UTC, fagubla requested changes

2024-01-02 17:01 UTC, fagubla commented on resources/js/processes-catalogue/components/ProcessTab.vue
> +    let pmql = "";
use a correct indentation

2024-01-02 17:11 UTC, tokensPM commented
QA server was successfully deployed https://ci-7ff8c20262.eng.processmaker.net

2024-01-02 18:14 UTC, CarliPinell commented on resources/js/processes-catalogue/components/ProcessInfo.vue
> +      :process="process"
solved

2024-01-02 18:15 UTC, CarliPinell commented on resources/js/processes-catalogue/components/ProcessTab.vue
> +            :descriptionText="$t('All your requests will be shown here')"
solved

2024-01-02 18:16 UTC, CarliPinell commented on resources/js/processes-catalogue/components/ProcessTab.vue
> +            :descriptionText="
solved

2024-01-02 18:18 UTC, CarliPinell commented on resources/js/processes-catalogue/components/ProcessTab.vue
> +    let pmql = "";
Solved

2024-01-02 18:41 UTC, tokensPM commented
QA server was successfully deployed https://ci-7ff8c20262.eng.processmaker.net

2024-01-02 18:45 UTC, fagubla approved these changes

2024-01-03 12:18 UTC, tokensPM commented
QA server was successfully deployed https://ci-7ff8c20262.eng.processmaker.net

2024-01-03 18:08 UTC, ana-mauricio requested changes
The message "The version was saved" still appears when there is required field like description
As shown in the following video
@CarliPinell 
https://github.com/ProcessMaker/processmaker/assets/21198450/50831c29-d7e4-4b97-8ffa-2eeb51d42f72

2024-01-03 18:29 UTC, CarliPinell commented
> The message "The version was saved" still appears when there is required field like description As shown in the following video @CarliPinell https://github.com/ProcessMaker/processmaker/assets/21198450/50831c29-d7e4-4b97-8ffa-2eeb51d42f72

The problem reported was solved.

2024-01-04 12:24 UTC, tokensPM commented
QA server was successfully deployed https://ci-7ff8c20262.eng.processmaker.net

2024-01-04 13:40 UTC, fagubla requested changes

2024-01-04 13:40 UTC, fagubla commented on resources/js/components/shared/ModalSaveVersion.vue
> +
remove blank line

2024-01-04 13:40 UTC, fagubla commented on resources/js/components/shared/ModalSaveVersion.vue
> +
remove blank line

2024-01-05 11:58 UTC, CarliPinell commented on resources/js/components/shared/ModalSaveVersion.vue
> +
solved

2024-01-05 11:58 UTC, CarliPinell commented on resources/js/components/shared/ModalSaveVersion.vue
> +
solved

2024-01-05 12:20 UTC, tokensPM commented
QA server was successfully deployed https://ci-7ff8c20262.eng.processmaker.net

2024-01-05 13:28 UTC, ana-mauricio commented
During the revision of the PR The following issues were detected:

- https://processmaker.atlassian.net/browse/FOUR-13095
- https://processmaker.atlassian.net/browse/FOUR-13089
- https://processmaker.atlassian.net/browse/FOUR-13086
- https://processmaker.atlassian.net/browse/FOUR-13084
- https://processmaker.atlassian.net/browse/FOUR-13082
- https://processmaker.atlassian.net/browse/FOUR-13080
- https://processmaker.atlassian.net/browse/FOUR-13079
@CarliPinell @boliviacoca

2024-01-05 19:30 UTC, tokensPM commented
QA server was successfully deployed https://ci-7ff8c20262.eng.processmaker.net

2024-01-05 20:19 UTC, tokensPM commented
QA server was successfully deployed https://ci-7ff8c20262.eng.processmaker.net

2024-01-05 20:57 UTC, tokensPM commented
QA server was successfully deployed https://ci-7ff8c20262.eng.processmaker.net

2024-01-05 22:02 UTC, fagubla requested changes

2024-01-05 22:02 UTC, fagubla commented on resources/js/processes-catalogue/components/TaskTab.vue
> +        <div class="bg-white" v-if="!showTabTasks">
use a correct indentation

2024-01-05 22:04 UTC, CarliPinell commented on resources/js/processes-catalogue/components/RequestTab.vue
> +        <div class="bg-white" v-if="!showTabRequests">
solved

2024-01-05 22:06 UTC, CarliPinell commented on resources/js/processes-catalogue/components/TaskTab.vue
> +        <div class="bg-white" v-if="!showTabTasks">
solved

2024-01-05 22:08 UTC, CarliPinell commented on resources/js/processes-catalogue/components/ProcessesCatalogue.vue
> +            :current-user="currentUser"
No. "currentUser" is an entire Object with more attributes. Variable "currentUserId" was not touch to avoid crashes in other components.

2024-01-05 22:25 UTC, tokensPM commented
QA server was successfully deployed https://ci-7ff8c20262.eng.processmaker.net

2024-01-05 22:56 UTC, tokensPM commented
QA server was successfully deployed https://ci-7ff8c20262.eng.processmaker.net

2024-01-05 23:39 UTC, tokensPM commented
QA server was successfully deployed https://ci-7ff8c20262.eng.processmaker.net

2024-01-08 14:45 UTC, ana-mauricio approved these changes

2024-01-08 14:53 UTC, fagubla approved these changes

2024-01-08 19:55 UTC, merged