FOUR-13038 Fix Login blocked because invalid 2FA settings
ProcessMaker/processmaker pull request #5899
Opened 2024-01-02 19:54 UTC by caleeli

## Issue & Reproduction Steps

1. Log in to an instance without Email Server configured
2. Create a new user
3. Go to admin tab
4. Click on settings in sidebar menu
5. Click on Log in option
6. Enable 2FA
7. Select By email option
8. Log in in other browser with new user
9. Fill username
10. Fill password

## Solution
- Add a validation before to enable the email and sms options.

## How to Test

1. Log in to an instance without Email Server configured
2. Create a new user
3. Go to admin tab
4. Click on settings in sidebar menu
5. Click on Log in option
6. Enable 2FA
7. Select By email option
8. Validation will be triggered

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-13038

## Code Review Checklist
- [x] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [x] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [x] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [x] This solution fixes the bug reported in the original ticket.
- [x] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [x] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [x] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [x] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [x] This ticket conforms to the PRD associated with this part of ProcessMaker.

2024-01-02 20:19 UTC, tokensPM commented
QA server was successfully deployed https://ci-cd0b46d888.eng.processmaker.net

2024-01-03 16:59 UTC, devmiguelangel commented on resources/views/auth/2fa/email_test.blade.php
> +  <title>{{ __("Test email server status")</title>
close brackets

```suggestion
  <title>{{ __("Test email server status") }}</title>
```

2024-01-03 17:00 UTC, devmiguelangel commented on resources/views/auth/2fa/email_test.blade.php
> +  <p>{{ __("Test email server status")</p>
close brackets

```suggestion
  <p>{{ __("Test email server status") }}</p>
```

2024-01-03 17:14 UTC, devmiguelangel commented on resources/js/admin/settings/components/SettingCheckboxes.vue
> +      message: "",
use single quotes

```suggestion
      message: '',
```

2024-01-03 17:14 UTC, devmiguelangel commented on resources/js/admin/settings/components/SettingCheckboxes.vue
> +      this.message = "";
use single quotes

```suggestion
      this.message = '';
```

2024-01-03 17:15 UTC, devmiguelangel commented on resources/js/admin/settings/components/SettingCheckboxes.vue
> +      if (this.ui("dynamic")) {
use single quotes

```suggestion
      if (this.ui('dynamic')) {
```

2024-01-03 17:15 UTC, devmiguelangel commented on resources/js/admin/settings/components/SettingCheckboxes.vue
> +      this.message = "";
use single quotes

```suggestion
      this.message = '';
```

2024-01-03 17:15 UTC, devmiguelangel commented on resources/js/admin/settings/components/SettingCheckboxes.vue
> +      const testSettingEndpoint = this.ui("testSettingEndpoint");
use single quotes

```suggestion
      const testSettingEndpoint = this.ui('testSettingEndpoint');
```

2024-01-03 17:16 UTC, devmiguelangel commented on ProcessMaker/Http/Controllers/Auth/TwoFactorAuthController.php
> +
Remove line
```suggestion
```

2024-01-03 17:17 UTC, devmiguelangel commented on ProcessMaker/Http/Controllers/Auth/TwoFactorAuthController.php
> +                    'body' => $body
add comma
```suggestion
                    'body' => $body,
```

2024-01-03 17:19 UTC, devmiguelangel commented on ProcessMaker/Http/Controllers/Auth/TwoFactorAuthController.php
> +                ]
add comma
```suggestion
                ],
```

2024-01-03 17:23 UTC, devmiguelangel requested changes
@caleeli I put some comments

2024-01-03 19:07 UTC, devmiguelangel approved these changes

2024-01-03 23:08 UTC, merged

2024-01-08 22:21 UTC, tokensPM commented
QA server was successfully deployed https://ci-cd0b46d888.eng.processmaker.net