feature/FOUR-12702: Start a Request: we need to enable only if the user was assigned "Start Permission"
ProcessMaker/processmaker pull request #5934
Opened 2024-01-05 20:59 UTC by luNunezProcessmaker

## Issue & Reproduction Steps

1. Create a process with start event
2. Assign a specific user or group 
3. Go to Processes and Start a request with a different user not assigned in the Start Permission
4. Go to Processes and Start a request with a different user not assigned in the group Start Permission
5. The START THIS PROCESS can not enable if the user was not assigned in the “Start Permission“

When the user does not have permission or the process does not have any start request to show use this style… disable the button

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-12702
- https://processmaker.atlassian.net/browse/FOUR-12788

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next

2024-01-08 16:44 UTC, tokensPM commented
QA server was successfully deployed https://ci-3a4af8a104.eng.processmaker.net

2024-01-10 12:07 UTC, fagubla requested changes

2024-01-10 12:07 UTC, fagubla commented on resources/js/processes-catalogue/components/ProcessOptions.vue
> +    <buttons-start :process="process"/>
Expected a space before '/>'

2024-01-10 13:21 UTC, pmPaulis requested changes

2024-01-10 13:21 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/ProcessController.php
> +    public function startEvents(Request $request, Process $process)
Add the unit test related to this function

2024-01-10 13:21 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/ProcessController.php
> +    protected function checkUsersGroup($event, int $groupId, Request $request)
Add the unit test related to this function

2024-01-11 18:10 UTC, fagubla approved these changes

2024-01-11 20:35 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/ProcessController.php
> +    public function startEvents(Request $request, Process $process)
https://processmaker.atlassian.net/browse/FOUR-12702

2024-01-11 20:36 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/ProcessController.php
> +    protected function checkUsersGroup($event, int $groupId, Request $request)
https://processmaker.atlassian.net/browse/FOUR-12702

2024-01-11 23:15 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-e25ca07418.engk8s.processmaker.net

2024-01-12 02:50 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-e25ca07418.engk8s.processmaker.net

2024-01-12 15:38 UTC, pmPaulis commented
I reviewed the following use cases:
https://github.com/ProcessMaker/processmaker/assets/42388723/5dc0d84b-3255-4a3a-8a6b-b71b50e9e7c6

2024-01-12 18:12 UTC, pmPaulis approved these changes

2024-01-12 18:13 UTC, merged