QA Observation bugfix/FOUR-13084: Requests are not refreshed when switching between My Requests/My Task tabs in Launch Pad
ProcessMaker/processmaker pull request #5955
Opened 2024-01-08 21:01 UTC by CarliPinell

## How to Test
-  Open Any Process with "Open in Launchpad" 
-  Create a new request in other window
- Change from tab Request to Task and vice versa

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-13084

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.
ci:deploy
ci:next

2024-01-08 21:22 UTC, tokensPM commented
QA server was successfully deployed https://ci-c95a3be734.eng.processmaker.net

2024-01-08 21:28 UTC, fagubla requested changes

2024-01-08 21:28 UTC, fagubla commented on resources/js/processes-catalogue/components/ProcessTab.vue
> +    <b-tabs content-class="text-style" lazy>
Apply code style

2024-01-09 05:27 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-966e8bebee.engk8s.processmaker.net

2024-01-09 12:24 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-966e8bebee.engk8s.processmaker.net

2024-01-09 13:04 UTC, fagubla approved these changes

2024-01-09 16:57 UTC, merged