Observation/FOUR-13145: Update Login Screen Marketing Text for Winter
ProcessMaker/processmaker pull request #5962
Opened 2024-01-09 16:14 UTC by agustinbusso

## Issue & Reproduction Steps
Added changes according to the ticket https://processmaker.atlassian.net/browse/FOUR-13145 and the figma [Platform general Design](https://www.figma.com/proto/sLB2dU5va9iuyKf8Yb8Yjb/Platform-general-Design?page-id=563%3A354&type=design&node-id=563-356&viewport=-8637%2C-3381%2C0.68&t=ot76pTvGabdNWXSt-1&scaling=min-zoom&starting-point-node-id=563%3A356&mode=design)

2024-01-10 18:52 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-7ba73b21bf.engk8s.processmaker.net

2024-01-11 15:12 UTC, caleeli commented on resources/views/auth/newLogin.blade.php
> +                <img src="/img/proceC2.svg" class="mr-2 procesC2-icon" alt="ProceC2" />
Consider to change the `alt` content to a simple description, could be `ProcessMaker Bot`

2024-01-11 17:21 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-7ba73b21bf.engk8s.processmaker.net

2024-01-11 18:05 UTC, caleeli approved these changes

2024-01-12 14:13 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-7ba73b21bf.engk8s.processmaker.net

2024-01-12 15:39 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-7ba73b21bf.engk8s.processmaker.net

2024-01-12 17:46 UTC, pmPaulis commented
@agustinbusso 
The font is not the same defined in figma
![image](https://github.com/ProcessMaker/processmaker/assets/42388723/c657374d-1b92-496f-b014-2bde8256278d)
![image](https://github.com/ProcessMaker/processmaker/assets/42388723/ea7ef3a9-1716-487a-aac5-617ebf2166f5)
Regards,

2024-01-17 13:34 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-7ba73b21bf.engk8s.processmaker.net

2024-01-18 01:56 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-7ba73b21bf.engk8s.processmaker.net

2024-01-18 11:51 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-7ba73b21bf.engk8s.processmaker.net

2024-01-18 15:46 UTC, ryancooley requested changes

2024-01-18 15:46 UTC, ryancooley commented on public/images/no-results.svg
Do we know why this and another image are being added in this PR? @agustinbusso

2024-01-18 16:41 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-7ba73b21bf.engk8s.processmaker.net

2024-01-18 22:08 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-7ba73b21bf.engk8s.processmaker.net

2024-01-18 22:38 UTC, danloa approved these changes

2024-01-19 01:21 UTC, ryancooley approved these changes

2024-01-19 01:22 UTC, merged