FOUR-13025:Message: when there are no processes available in a category
ProcessMaker/processmaker pull request #5967
Opened 2024-01-09 20:34 UTC by fagubla

## Issue & Reproduction Steps
Describe the issue this ticket solves and describe how to reproduce the issue (please attach any fixtures used to reproduce the issue).

## Solution
- List the changes you've introduced to solve the issue.

## How to Test
Describe how to test that this solution works.

## Related Tickets & Packages
- [FOUR-13025](https://processmaker.atlassian.net/browse/FOUR-13025)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

2024-01-09 21:50 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-75ec80b594.engk8s.processmaker.net

2024-01-10 13:25 UTC, pmPaulis approved these changes

2024-01-11 21:08 UTC, pmPaulis commented
Issue https://processmaker.atlassian.net/browse/SCO-21109

2024-01-12 01:40 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-75ec80b594.engk8s.processmaker.net

2024-01-12 03:46 UTC, ryancooley requested changes

2024-01-12 03:46 UTC, ryancooley commented on resources/img/launchpad-images/empty-process.png
Please replace this with an SVG or use the Font Awesome icon `fa-umbrella-beach`.

2024-01-12 15:00 UTC, fagubla commented on resources/img/launchpad-images/empty-process.png
The image was replaced by a SVG

2024-01-12 15:32 UTC, ryancooley requested changes

2024-01-12 15:32 UTC, ryancooley commented on resources/img/launchpad-images/empty-process.png
@fagubla I'm sorry but this image is now just an SVG wrapper of a PNG image. It should be an actual SVG or preferably the Font Awesome icon since we have already used that icon in other areas of the platform.

cc: @pmPaulis

2024-01-12 15:46 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-75ec80b594.engk8s.processmaker.net

2024-01-12 16:50 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-75ec80b594.engk8s.processmaker.net

2024-01-12 18:09 UTC, merged