QA observation bugfix/FOUR-12799: Select lists are different controls in the launch pad modal
ProcessMaker/processmaker pull request #5977
Opened 2024-01-10 16:08 UTC by CarliPinell

## How to Test
-  Open Any Process with "Open in Launchpad"
- Check both Dropdowns/Select List sizes

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-12799

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.
ci:deploy
ci:next

2024-01-10 16:51 UTC, fagubla requested changes

2024-01-10 16:51 UTC, fagubla commented on resources/js/components/shared/IconDropdown.vue
> +        );
keep it in a single line

2024-01-10 16:52 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-b715487f89.engk8s.processmaker.net

2024-01-10 16:56 UTC, CarliPinell commented on resources/js/components/shared/IconDropdown.vue
> +        );
Ok. solved

2024-01-10 17:08 UTC, fagubla approved these changes

2024-01-10 17:30 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-b715487f89.engk8s.processmaker.net

2024-01-10 20:35 UTC, pmPaulis commented
@CarliPinell 
Please review the height is not the same...
Please add a place holder in the icon to Select Icon
![image](https://github.com/ProcessMaker/processmaker/assets/42388723/a28c2676-e8a6-4301-a27a-c75ef7e3701a)

2024-01-11 18:23 UTC, ana-mauricio requested changes
HI @CarliPinell The text for icon 
![image](https://github.com/ProcessMaker/processmaker/assets/21198450/6f66e544-0a93-4dde-85cb-895df483e6fb)

It is not well centered, it seems to be at the top unlike the other select list
@ana-mauricio Last observation was fixed.

2024-01-11 19:45 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-b715487f89.engk8s.processmaker.net

2024-01-11 20:25 UTC, pmPaulis commented
Carlos please replace Icon to Select Icon
![image](https://github.com/ProcessMaker/processmaker/assets/42388723/163558a9-b2a7-4b42-a1f0-9abe5f3ed58b)

2024-01-11 21:04 UTC, ana-mauricio approved these changes

2024-01-12 03:27 UTC, ryancooley commented
> Carlos please replace Icon to Select Icon ![image](https://private-user-images.githubusercontent.com/42388723/296042371-163558a9-b2a7-4b42-a1f0-9abe5f3ed58b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzAyMjksIm5iZiI6MTcwNTAyOTkyOSwicGF0aCI6Ii80MjM4ODcyMy8yOTYwNDIzNzEtMTYzNTU4YTktYjJhNy00YjQyLWExZjAtOWFiZTVmM2VkNThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAzMjUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ZmQ2MWQ2MjhkMjhkZjNjYzE1MGFkNjFiZDhmM2QxMThiNGFjYmNkY2Y1ZWQxMTA3YTZmZjQ0MmQ2MjAxNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k0qxnUh1dAMpB9YZqydybhu2pDlrqOZaJ2i4WPSmJ3c)

@CarliPinell Has this observation been addressed?

cc: @pmPaulis

2024-01-12 13:33 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-b715487f89.engk8s.processmaker.net

2024-01-12 13:36 UTC, merged