Feature/four 13250: Action Unauthorized: when the user does not have permission to start a Request
ProcessMaker/processmaker pull request #6032
Opened 2024-01-15 16:59 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
**Steps**

1. Create a new user
2. Login with this user
3. Go to Lauchpad and open the process

**Current behavior**
The following error apears
![Screenshot from 2024-01-15 11-15-24](https://github.com/ProcessMaker/processmaker/assets/123644082/570e56cf-d762-44a6-9693-de5aaf22dda4)

**Expected behavior**
when the user does not have permission to start a case the button needs to disable
## Related Tickets & Packages
- Link to any related FOUR tickets, PRDs, or packages

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy

2024-01-15 17:17 UTC, pmPaulis commented
@luNunezProcessmaker please upload a video with your test

2024-01-15 17:23 UTC, luNunezProcessmaker commented
Test:

https://github.com/ProcessMaker/processmaker/assets/123644082/bbe90a03-f6a5-4e0c-9879-4fdc0cc722f1

2024-01-15 18:53 UTC, fagubla approved these changes

2024-01-16 00:46 UTC, pmPaulis requested changes

2024-01-16 00:46 UTC, pmPaulis commented on routes/api.php
> +    Route::get('process_bookmarks/processes/{process}/start_events',
Please apply the following CS:
```
Route::get('process_bookmarks/processes/{process}/start_events', [ProcessController::class, 'startEvents'])
->name('processes.start.events')
->middleware($middlewareCatalog);
```
or
```
Route::get(
    'process_bookmarks/processes/{process}/start_events',
    [ProcessController::class, 'startEvents']
)->name('processes.start.events')->middleware($middlewareCatalog);
```

2024-01-16 00:46 UTC, pmPaulis commented on resources/js/processes-catalogue/components/optionsMenu/ButtonsStart.vue
> +          this.havelessOneStartEvent = true;
Please create a method to disable the button and use this method

2024-01-16 02:28 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-3864e33012.engk8s.processmaker.net

2024-01-18 00:50 UTC, merged