QA Observation Bugfix/FOUR-13236: Error in console when clicking on a process box
ProcessMaker/processmaker pull request #6051
Opened 2024-01-17 15:21 UTC by CarliPinell

## Solution
- Reported console error was fixed

## How to Test
- Go to Process Catalogue
- Click on some Available Process Category
- Click on Any Process
- Check browser console

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-13236

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.
ci:deploy
ci:next

2024-01-17 16:08 UTC, fagubla requested changes

2024-01-17 16:08 UTC, fagubla commented on ProcessMaker/PackageHelper.php
> +    const PM_PACKAGE_SAVEDSEARCH = 'ProcessMaker\Package\SavedSearch\SavedSearchServiceProvider';
PM_PACKAGE_SAVED_SEARCH

2024-01-17 16:15 UTC, CarliPinell commented on ProcessMaker/PackageHelper.php
> +    const PM_PACKAGE_SAVEDSEARCH = 'ProcessMaker\Package\SavedSearch\SavedSearchServiceProvider';
Solved

2024-01-17 16:52 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-1bc643fd3c.engk8s.processmaker.net

2024-01-17 17:23 UTC, pmPaulis commented
@CarliPinell 
The issue is still replicating in the build generated
![image](https://github.com/ProcessMaker/processmaker/assets/42388723/bcd81774-b694-4edc-83bd-a2613f9aacc2)

2024-01-17 19:39 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-1bc643fd3c.engk8s.processmaker.net

2024-01-18 12:39 UTC, fagubla approved these changes

2024-01-18 13:34 UTC, pmPaulis commented
@CarliPinell 
The issue does not replicate but the following use case is not working in Open Modeler:

2024-01-18 17:05 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-1bc643fd3c.engk8s.processmaker.net

2024-01-18 22:27 UTC, pmPaulis commented
@CarliPinell 
It works as expected
![image](https://github.com/ProcessMaker/processmaker/assets/42388723/630724ae-4c01-4429-9d08-bcfc77864c1d)
![image](https://github.com/ProcessMaker/processmaker/assets/42388723/8823fd94-ee1e-447d-b1ae-b80b2c9b7b71)

2024-01-18 22:27 UTC, pmPaulis approved these changes

2024-01-19 01:24 UTC, merged