FOUR-13307:The process table takes at least 10 seconds to load processes
ProcessMaker/processmaker pull request #6087
Opened 2024-01-19 21:22 UTC by fagubla

## Issue & Reproduction Steps
1.Log in
2.Go to Designer
3.Click on View all process

**Current Behavior:**

The process loading takes at least 10 seconds, the spinner is lost and shows the blank table for a few seconds

## Solution
- List the changes you've introduced to solve the issue.

## How to Test
Describe how to test that this solution works.

## Related Tickets & Packages
- [FOUR-13307](https://processmaker.atlassian.net/browse/FOUR-13307)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

2024-01-19 21:56 UTC, gustavobascope approved these changes
No observations

2024-01-19 22:12 UTC, nolanpro requested changes

2024-01-19 22:12 UTC, nolanpro commented on resources/js/processes/components/ArchivedProcessList.vue
> +>>>>>>> 9ed828451b1a6a04cdefc40bb15eb64bee43d488
@fagubla this has merge conflicts comitted

2024-01-19 23:31 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-a25098fa53.engk8s.processmaker.net

2024-01-20 00:05 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-a25098fa53.engk8s.processmaker.net

2024-01-20 00:57 UTC, merged