Feature/FOUR-14120: Backend - Fire job when task is assigned to a user
ProcessMaker/processmaker pull request #6257
Opened 2024-02-20 18:17 UTC by CarliPinell

## Solution
- A Listener for the ActivityAssigned event in ProcessMaker/Providers/ProcessMakerServiceProvider.php was added in registerEvents method
- A Dispatch method for SmartInbox job was added.

## How to Test
- Create Inbox Rules
- Start a new request

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-14120

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.
ci:deploy

2024-02-20 19:26 UTC, nolanpro requested changes

2024-02-21 12:05 UTC, CarliPinell commented on ProcessMaker/Providers/ProcessMakerServiceProvider.php
> +            SmartInbox::dispatch($processRequestToken);
Solved.

2024-02-21 12:17 UTC, CarliPinell commented on ProcessMaker/Jobs/SmartInbox.php
> +    public function __construct(ProcessRequestToken $incomingTask)
Solved.

2024-02-21 12:44 UTC, CarliPinell commented on ProcessMaker/InboxRules/ApplyAction.php
> +    public function applyActionOnTask(ProcessRequestToken $task)
in Progress.

2024-02-27 16:39 UTC, closed without merging

2024-02-27 16:39 UTC, boliviacoca commented
Closing