feature/FOUR-13702: UI: Process Information - Add Header Collapsible
ProcessMaker/processmaker pull request #6329
Opened 2024-03-04 16:01 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
![image-20240220-184049](https://github.com/ProcessMaker/processmaker/assets/123644082/6d84081a-fee4-4ce8-bf15-9f0d4b7c139e)

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-13702

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

2024-03-04 16:52 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-a2ccc344f7.engk8s.processmaker.net

2024-03-04 19:11 UTC, ana-mauricio requested changes
The button Start this Process does not have the white line separation 
![image](https://github.com/ProcessMaker/processmaker/assets/21198450/ab1c044d-3292-4b65-8e18-52184fd0513b)

There are not the same separation between button on the header 
![image](https://github.com/ProcessMaker/processmaker/assets/21198450/fdf63bcf-6312-4dd2-a742-465b56644d60)
 
As show in the figma
@luNunezProcessmaker

2024-03-05 12:13 UTC, fagubla requested changes

2024-03-05 12:13 UTC, fagubla commented on resources/js/processes-catalogue/components/ProcessCollapseInfo.vue
> +      auxBookmarkId: this.process.bookmark_id,
validate if `bookmark_id` exists

2024-03-05 12:13 UTC, fagubla commented on resources/js/processes-catalogue/components/ProcessCollapseInfo.vue
> +              />
the only thing that changes is the class, so 
```javascript
class="fas fa-bookmark"
:class="{ marked: showBookmarkIcon, unmarked: !showBookmarkIcon  }"
```

2024-03-05 14:19 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-a2ccc344f7.engk8s.processmaker.net

2024-03-05 16:43 UTC, fagubla approved these changes

2024-03-05 19:11 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-a2ccc344f7.engk8s.processmaker.net

2024-03-06 20:24 UTC, merged