Feature/four 11726: FOUR-11509: Create the new component to load the submenus in right
ProcessMaker/processmaker pull request #6372
Opened 2024-03-08 18:31 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
![image-20231107-192312](https://github.com/ProcessMaker/processmaker/assets/123644082/38fe9595-a30d-40b4-87ad-b1df6dd9987b)

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-11726

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy

2024-03-08 19:02 UTC, fagubla requested changes

2024-03-08 19:50 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-47ba7ce1f1.engk8s.processmaker.net

2024-03-08 20:21 UTC, pmPaulis requested changes

2024-03-08 20:21 UTC, pmPaulis commented on resources/js/admin/settings/components/SettingsMenu.vue
> +      group: "Action by Email",
Please not use a harcoded value, what happen in the Action by Email label was renamed?
Maybe the current value selected is the firstOption from the firstMenu

2024-03-08 20:23 UTC, pmPaulis commented
@luNunezProcessmaker 
This is not working we can see the following issues:
![image](https://github.com/ProcessMaker/processmaker/assets/42388723/8829f428-c576-474c-ac94-2bc721a489e7)

2024-03-08 21:03 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-47ba7ce1f1.engk8s.processmaker.net

2024-03-11 15:13 UTC, fagubla approved these changes

2024-03-11 19:58 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-47ba7ce1f1.engk8s.processmaker.net

2024-03-11 20:15 UTC, merged