feature/FOUR-14385: STORY Process Catalog updates
ProcessMaker/processmaker pull request #6400
Opened 2024-03-13 14:30 UTC by luNunezProcessmaker

## Issue & Reproduction Steps

- The Figma includes a desig for the Searches in categories to clear the searh (Review Figma ¨Search Categories).
- The Figma includes a design for a result that may be was broke or something was wrong, the message will be “Something went wrong Please try again in a few moments, or contact your admin if the problem persists.” review Figma: “Browser Clarifications”.

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-14385

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

2024-03-13 18:14 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-686d56c9fb.engk8s.processmaker.net

2024-03-14 00:49 UTC, pmPaulis commented
@luNunezProcessmaker please review the image
![image](https://github.com/ProcessMaker/processmaker/assets/42388723/c05e94f2-ac8a-4adb-a3d9-7196918f4a1f)

2024-03-14 00:52 UTC, pmPaulis requested changes

2024-03-14 00:52 UTC, pmPaulis commented on resources/js/processes-catalogue/components/utils/EmptySearch.vue
> +          src="/img/launchpad-images/emptyResults.svg"
This image exist?

2024-03-14 14:09 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-686d56c9fb.engk8s.processmaker.net

2024-03-14 14:49 UTC, pmPaulis requested changes

2024-03-14 14:49 UTC, pmPaulis commented on resources/js/processes-catalogue/components/utils/EmptySearch.vue
>        {{ $t("No Processes Available") }}
Please update this label according FIGMA:
`No results to show`
Please consider the translations too

2024-03-14 16:35 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-686d56c9fb.engk8s.processmaker.net

2024-03-14 16:54 UTC, fagubla approved these changes

2024-03-14 17:22 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-686d56c9fb.engk8s.processmaker.net

2024-03-15 17:18 UTC, merged