feature/FOUR-13852
ProcessMaker/processmaker pull request #6426
Opened 2024-03-18 16:42 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
The change related to the ModalSaveVersion will updated from Engines Team

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-13852

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:develop
ci:next

2024-03-18 18:23 UTC, fagubla requested changes

2024-03-18 18:23 UTC, fagubla commented on resources/js/components/shared/LaunchpadSettingsModal.vue
> +    saveFromEditLaunchpad() {
this is not necessary

2024-03-18 18:23 UTC, fagubla commented on resources/js/components/shared/LaunchpadSettingsModal.vue
> +      promise
this promise make change in the version, it's not necessary

2024-03-18 18:23 UTC, fagubla commented on resources/js/components/shared/LaunchpadSettingsModal.vue
> +      if (this.origin !== "core") {
review why is doing this if statement? and if is necessary origin

2024-03-19 14:53 UTC, pmPaulis requested changes

2024-03-19 14:53 UTC, pmPaulis commented on resources/js/components/shared/LaunchpadSettingsModal.vue
> +<style lang="scss">
please add scoped

2024-03-19 14:53 UTC, pmPaulis commented on resources/js/components/shared/LaunchpadSettingsModal.vue
> +              <span class="ml-2 custom-text">{{ selectedSavedChart || 'Select Chart' }}</span>
Add the translation for `'Select Chart'`

2024-03-19 14:53 UTC, pmPaulis commented on resources/js/components/shared/LaunchpadSettingsModal.vue
> +              {{ item.title || 'Select Chart' }}
Add the translation for 'Select Chart'

2024-03-21 17:30 UTC, closed without merging