feature/FOUR-14548: Launchpad Setup - Embed Media - part 2
ProcessMaker/processmaker pull request #6506
Opened 2024-03-27 18:12 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
![image-20240311-150141](https://github.com/ProcessMaker/processmaker/assets/123644082/c1d8c7e2-5006-470d-90a0-84336dd0b14c)

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-14548

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

2024-03-27 19:16 UTC, pmPaulis requested changes

2024-03-27 19:16 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/ProcessController.php
> +                            $fakeFile = File::image('photo.jpg');
Please upload a image in the `resources/img/launchpad-images/embed.png `
Use this image in this section download the image icon related to embed

2024-03-27 19:18 UTC, pmPaulis requested changes

2024-03-27 19:18 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/ProcessController.php
> +use Illuminate\Http\Testing\File;
Remove this use

2024-03-27 19:18 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/ProcessController.php
> +    const CAROUSEL_FILE_TYPES = [
Rename to CAROUSEL_TYPES

2024-03-27 19:32 UTC, fagubla requested changes

2024-03-27 19:32 UTC, fagubla commented on resources/js/components/shared/InputImageCarousel.vue
> +        url = new URL(urlString);
`const url = new URL(urlString)`

2024-03-27 19:32 UTC, fagubla commented on resources/js/components/shared/InputImageCarousel.vue
> +      return url.protocol === "http:" || url.protocol === "https:";
move to section try

2024-03-28 16:26 UTC, fagubla approved these changes

2024-03-29 01:36 UTC, pmPaulis requested changes

2024-03-29 01:36 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/ProcessController.php
> +                            $process
Create a method to save the image in the media table

2024-03-29 01:36 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/ProcessController.php
> +                            $process
Create a method to save the embed in the embed table

2024-04-01 20:17 UTC, fagubla requested changes

2024-04-01 20:17 UTC, fagubla commented on resources/js/components/shared/InputImageCarousel.vue
> +     * Check if embed files are valid
embed files?

2024-04-02 20:21 UTC, fagubla approved these changes

2024-04-02 20:57 UTC, closed without merging