Feature/four 14755
ProcessMaker/processmaker pull request #6566
Opened 2024-04-03 19:02 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
The new launch screen is not updated immediately. Reload is needed

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-14755

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy

2024-04-03 20:03 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-6171336eb4.engk8s.processmaker.net

2024-04-03 21:34 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-6171336eb4.engk8s.processmaker.net

2024-04-04 13:45 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-6171336eb4.engk8s.processmaker.net

2024-04-04 20:28 UTC, fagubla requested changes

2024-04-04 20:28 UTC, fagubla commented on resources/js/processes-catalogue/components/ProcessesCatalogue.vue
> +        console.log(this.process, this.launchpad);
remove this

2024-04-05 22:02 UTC, closed without merging