Feature/four 14796: Cancel in embed is not working launchPad
ProcessMaker/processmaker pull request #6606
Opened 2024-04-05 22:30 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
The Cancel button is not working the modal remains open

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-14796

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy

2024-04-05 23:30 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-68ed736fdb.engk8s.processmaker.net

2024-04-06 00:52 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-68ed736fdb.engk8s.processmaker.net

2024-04-08 15:45 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-68ed736fdb.engk8s.processmaker.net

2024-04-09 14:39 UTC, fagubla requested changes

2024-04-09 14:39 UTC, fagubla commented on resources/js/components/shared/InputImageCarousel.vue
> +</style>
add a line blank at the end

2024-04-09 14:58 UTC, pmPaulis approved these changes

2024-04-09 15:37 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-68ed736fdb.engk8s.processmaker.net

2024-04-09 23:28 UTC, merged