Update Terminology: Public Templates to Shared Templates
ProcessMaker/processmaker pull request #6629
Opened 2024-04-09 18:14 UTC by sanjacornelius

This PR updates all references of "Public Templates" to "Shared Templates" to better reflect the intended meaning and improve clarity within the application.

## Changes

- Replaced occurrences of "Public Templates" with "Shared Templates" throughout the codebase.

## How to Test

1. Navigate to the screen where "Public Templates" were referenced.
2. Verify that all instances now display "Shared Templates".
3. Check for consistency in terminology across different sections of the application.
4. Ensure that functionality related to shared templates remains unaffected.

## Related Tickets & Packages
- [FOUR-14872](https://processmaker.atlassian.net/browse/FOUR-14872)

ci:next
ci:deploy

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2024-04-09 19:24 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-765c5f1672.engk8s.processmaker.net

2024-04-10 19:37 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-765c5f1672.engk8s.processmaker.net

2024-04-10 21:23 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-765c5f1672.engk8s.processmaker.net

2024-04-11 16:24 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-765c5f1672.engk8s.processmaker.net

2024-04-11 16:40 UTC, mcraeteisha requested changes
Approved!

2024-04-11 18:21 UTC, merged