feature/FOUR-15127
ProcessMaker/processmaker pull request #6724
Opened 2024-04-19 16:11 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
When the process is collapsed it show all the description of the process 

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-15127

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy

2024-04-19 17:05 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-208794c5c6.engk8s.processmaker.net

2024-04-19 18:29 UTC, fagubla requested changes

2024-04-19 18:29 UTC, fagubla commented on resources/js/processes-catalogue/components/ProcessCollapseInfo.vue
> +      return nameEllipsis + "..."
for the short name the three dots will always be present

2024-04-19 21:40 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-208794c5c6.engk8s.processmaker.net

2024-04-19 22:36 UTC, pmPaulis requested changes

2024-04-19 22:36 UTC, pmPaulis commented on resources/js/processes-catalogue/components/ProcessScreen.vue
> +      console.log(name.length);
remove this console.log

2024-04-19 23:50 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-208794c5c6.engk8s.processmaker.net

2024-04-22 12:16 UTC, fagubla approved these changes

2024-04-22 12:17 UTC, fagubla requested changes

2024-04-22 12:17 UTC, fagubla commented on resources/js/processes-catalogue/components/ProcessScreen.vue
> +    }
add this method to the mixin file

2024-04-22 13:31 UTC, fagubla approved these changes

2024-04-22 13:48 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-208794c5c6.engk8s.processmaker.net

2024-04-22 14:09 UTC, CarliPinell approved these changes

2024-04-22 15:01 UTC, pmPaulis approved these changes

2024-04-22 23:14 UTC, merged