bugfix/FOUR-15393: Welcome Screen Filtering Project Assets is Not Very Automatic
ProcessMaker/processmaker pull request #6830
Opened 2024-05-06 16:54 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
List is not updated automatically, we need to click on an arrow for filtering on the table to update it.
## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-15393

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

2024-05-06 17:55 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-fb2c715d53.engk8s.processmaker.net

2024-05-06 19:57 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-fb2c715d53.engk8s.processmaker.net

2024-05-07 15:00 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-fb2c715d53.engk8s.processmaker.net

2024-05-07 15:58 UTC, fagubla requested changes

2024-05-07 15:58 UTC, fagubla commented on resources/js/processes/designer/RecentAssets.vue
> +      console.log("jiji");
remove console

2024-05-07 15:59 UTC, fagubla commented on resources/js/processes/designer/RecentAssets.vue
> +    waitingForUpdate() {
this is not working as the expected

2024-05-07 16:53 UTC, fagubla approved these changes

2024-05-07 17:52 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-fb2c715d53.engk8s.processmaker.net

2024-05-07 19:07 UTC, merged