FOUR-15401:The request list disappears with the selection of 30 or 50 items per page, LaunchPad
ProcessMaker/processmaker pull request #6832
Opened 2024-05-06 19:25 UTC by fagubla

## Issue & Reproduction Steps
1.Go to /process-browser
2.Find a process with more than 15 requests created (eg: Verify Message Events)
3.Click on the process and see the requests
4.Go to the second page of the requests
5.Select 30 or 50 items

**Current Behavior:**

The list of requests disappears.

## Solution
- List the changes you've introduced to solve the issue.

## How to Test
Describe how to test that this solution works.

## Related Tickets & Packages
- [FOUR-15401](https://processmaker.atlassian.net/browse/FOUR-15401)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy

2024-05-06 20:04 UTC, luNunezProcessmaker approved these changes

2024-05-06 20:19 UTC, gustavobascope approved these changes
Approved
[Screencast from 06-05-24 16:16:24.webm](https://github.com/ProcessMaker/processmaker/assets/129873111/107b789e-984c-4c4f-b867-fc3bf1e3c966)

2024-05-06 20:25 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-f8f28a29b0.engk8s.processmaker.net

2024-05-06 20:52 UTC, pmPaulis approved these changes

2024-05-07 00:47 UTC, ryancooley requested changes

2024-05-07 00:47 UTC, ryancooley commented on resources/js/components/shared/PaginationTable.vue
> +      defaulPage: 1,
Please correct the spelling to `defaultPage`.

2024-05-07 00:47 UTC, ryancooley commented on resources/js/components/shared/PaginationTable.vue
> +      this.goToPage(this.defaulPage);
Please correct the spelling to `defaultPage`.

2024-05-07 00:58 UTC, merged