feature/FOUR-15751: Update the Process Information
ProcessMaker/processmaker pull request #6873
Opened 2024-05-23 20:52 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
- Consider the collapse for each section
- All the fields exist, only is a reorder

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-15751

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

2024-05-23 22:13 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-ed119a2916.engk8s.processmaker.net

2024-05-23 23:22 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-ed119a2916.engk8s.processmaker.net

2024-05-24 12:56 UTC, fagubla requested changes

2024-05-24 12:56 UTC, fagubla commented on resources/views/processes/edit.blade.php
> +                            >
use a correct indentation

2024-05-24 12:56 UTC, fagubla commented on resources/views/processes/edit.blade.php
> +                                    >
use a correct indentation

2024-05-24 12:56 UTC, fagubla commented on resources/views/processes/edit.blade.php
> +                                        >
use a correct indentation

2024-05-24 12:56 UTC, fagubla commented on resources/views/processes/edit.blade.php
> +                                            />
use a correct indentation

2024-05-24 12:56 UTC, fagubla commented on resources/views/processes/edit.blade.php
> +                                    >
use a correct indentation

2024-05-24 12:56 UTC, fagubla commented on resources/views/processes/edit.blade.php
> +                                                    >
use a correct indentation

2024-05-24 12:56 UTC, fagubla commented on resources/views/processes/edit.blade.php
> +                                                        >
use a correct indentation

2024-05-24 12:56 UTC, fagubla commented on resources/views/processes/edit.blade.php
> +                                                        >
use a correct indentation

2024-05-24 12:56 UTC, fagubla commented on resources/views/processes/edit.blade.php
> +                                    >
use a correct indentation

2024-05-24 12:56 UTC, fagubla commented on resources/views/processes/edit.blade.php
> +                                        >
use a correct indentation

2024-05-24 12:56 UTC, fagubla commented on resources/views/processes/edit.blade.php
> +                                            />
use a correct indentation

2024-05-24 12:56 UTC, fagubla commented on resources/views/processes/edit.blade.php
> +                                    >
use a correct indentation

2024-05-24 12:56 UTC, fagubla commented on resources/views/processes/edit.blade.php
> +                                                        >
use a correct indentation

2024-05-24 12:56 UTC, fagubla commented on resources/views/processes/edit.blade.php
> +                                                        >
use a correct indentation

2024-05-24 14:18 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-ed119a2916.engk8s.processmaker.net

2024-05-24 15:07 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-ed119a2916.engk8s.processmaker.net

2024-05-24 16:28 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-ed119a2916.engk8s.processmaker.net

2024-05-24 17:43 UTC, pmPaulis requested changes

2024-05-24 18:33 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-ed119a2916.engk8s.processmaker.net

2024-05-24 19:47 UTC, merged