FOUR-15153 Updated deps and ran prod script
ProcessMaker/processmaker pull request #6910
Opened 2024-06-05 03:22 UTC by josechirivella

ci:deploy
ci:next
ci:connector-docusign:FOUR-15153
ci:connector-idp:FOUR-15153
ci:connector-:pdf-printFOUR-15153
ci:connector-send-email:FOUR-15153
ci:connector-slack:FOUR-15153
ci:package-ab-testing:FOUR-15153
ci:package-actions-by-email:FOUR-15153
ci:package-collections:FOUR-15153
ci:package-conversational-forms:FOUR-15153
ci:package-data-sources:FOUR-15153
ci:package-dynamic-ui:FOUR-15153
ci:package-files:FOUR-15153
ci:package-googleplaces:FOUR-15153
ci:package-pm-blocks:FOUR-15153
ci:package-process-documenter:FOUR-15153
ci:package-savedsearch:FOUR-15153
ci:package-sentry:FOUR-15153
ci:package-translations:FOUR-15153
ci:package-webentry:FOUR-15153
ci:package-vocabularies:FOUR-15153
ci:package-versions:FOUR-15153

2024-06-05 05:03 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-6ee1c3adef.engk8s.processmaker.net

2024-06-05 14:37 UTC, pmPaulis requested changes

2024-06-05 14:37 UTC, pmPaulis commented on public/images/Stroke.svg
@josechirivella 
Could you remove this image, please?
Regards,

2024-06-10 04:20 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-6ee1c3adef.engk8s.processmaker.net

2024-06-10 04:33 UTC, merged