Feature/FOUR-14386: Update Cards (UI updated)
ProcessMaker/processmaker pull request #6973
Opened 2024-06-19 21:28 UTC by CarliPinell

## Solution
- Go to Processes menu
- Navigate through cards

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-14386

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2024-06-19 21:56 UTC, gustavobascope approved these changes
Approved

2024-06-20 18:23 UTC, gproly requested changes

2024-06-20 18:23 UTC, gproly commented on resources/js/processes-catalogue/components/utils/Card.vue
> +    <span v-if="cardMessage === 'show-more' && !loading"> {{ $t('Show More') }}</span>
Please add missing translations into en.json file

2024-06-20 18:23 UTC, gproly commented on resources/js/processes-catalogue/components/utils/Card.vue
> +    <span v-if="loading"><i class="fas fa-spinner fa-spin"></i> {{ $t('Loading') }}...</span>
Please add missing translations into en.json file

2024-06-20 20:38 UTC, CarliPinell commented on resources/js/processes-catalogue/components/utils/Card.vue
> +    <span v-if="cardMessage === 'show-more' && !loading"> {{ $t('Show More') }}</span>
Done

2024-06-20 20:38 UTC, CarliPinell commented on resources/js/processes-catalogue/components/utils/Card.vue
> +    <span v-if="loading"><i class="fas fa-spinner fa-spin"></i> {{ $t('Loading') }}...</span>
Done

2024-06-24 17:08 UTC, gproly approved these changes

2024-06-25 16:26 UTC, merged