FOUR-15804:Process Map - Behavior when the task has Screen, Image or …
ProcessMaker/processmaker pull request #6981
Opened 2024-06-24 20:04 UTC by henryjonathanquispe

## Solution
- Add navigation in screen, with multiple pages and images

## How to Test
- Open the modeler.
- Click the icon Slideshow in modeler
- Pickup the link "Open slideshow mode"
- Click on any node
- View the right panel
## Related Tickets & Packages
- 

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2024-06-24 20:33 UTC, fagubla approved these changes

2024-06-24 21:21 UTC, pmPaulis requested changes

2024-06-24 21:21 UTC, pmPaulis commented on resources/js/globalStore/index.js
> +        if (options.parent && options.parent.$globalStore) {
You can use this:
`if (options.parent?.$globalStore) {`

2024-06-24 22:18 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-b44424acb1.engk8s.processmaker.net

2024-06-25 14:42 UTC, pmPaulis approved these changes

2024-06-25 14:43 UTC, merged