Feature/four 15984: FOUR-15515: A flag needs to saved when the abe was executed
ProcessMaker/processmaker pull request #7053
Opened 2024-07-09 20:50 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
When a request was executed by action by email the following column needs to populated with 
 `process_request_tokens.is_actionbyemail = 1`
It means that the Request was closed by action by email actions

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-15984

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

2024-07-09 22:07 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-fb8fca10d5.engk8s.processmaker.net

2024-07-10 12:26 UTC, pmPaulis requested changes

2024-07-10 12:26 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
> +        return response()->json([], 200);
Return a boolean please

2024-07-10 12:26 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
> +    public function abeFlag($id)
rename this function to enableIsActionbyemail

2024-07-10 17:16 UTC, pmPaulis requested changes

2024-07-10 17:16 UTC, pmPaulis commented on ProcessMaker/Repositories/TokenRepository.php
> +                (new ProcessRequestController)->abeFlag($token->getKey());
please move the update is_Actionbyemail `TaskController::updateVariable`

2024-07-10 19:44 UTC, pmPaulis requested changes

2024-07-10 19:44 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/TaskController.php
> +                    (new ProcessRequestController)->abeFlag($task->id);
the function is given an error enableIsActionbyemail

2024-07-10 20:48 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-fb8fca10d5.engk8s.processmaker.net

2024-07-10 21:05 UTC, merged