Feature/four 16596
ProcessMaker/processmaker pull request #7060
Opened 2024-07-10 17:24 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
`$emailScreenCompleted = $configEmail->screenCompleteRef ?? 0;`

**Expected Behavior**
Create a method to show the screen completed after route a request

Create the test

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-16596

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

2024-07-10 20:34 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-095e4dadb2.engk8s.processmaker.net

2024-07-10 21:57 UTC, pmPaulis requested changes

2024-07-10 21:57 UTC, pmPaulis commented on ProcessMaker/Http/Controllers/TaskController.php
> +    private function showScreen($screenId)
Add the corresponding for this function

2024-07-11 22:38 UTC, pmPaulis requested changes

2024-07-11 22:38 UTC, pmPaulis commented on ProcessMaker/Repositories/TokenRepository.php
> +        if (!$isScriptOrServiceTask) {
Remove this if is repeat in the line 167

2024-07-12 01:05 UTC, pmPaulis approved these changes

2024-07-12 01:48 UTC, merged