feature/FOUR-17281
ProcessMaker/processmaker pull request #7179
Opened 2024-07-26 15:15 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
When the Action By email require login need to redirect to login page when the session does not exist

1. Enable action by email with login
2. Enable action by email without login

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-17281

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

2024-07-26 16:20 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-ced587ab00.engk8s.processmaker.net

2024-07-26 18:28 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-ced587ab00.engk8s.processmaker.net

2024-07-26 22:05 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-ced587ab00.engk8s.processmaker.net

2024-07-29 18:17 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-ced587ab00.engk8s.processmaker.net

2024-07-29 20:26 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-ced587ab00.engk8s.processmaker.net

2024-07-30 12:53 UTC, pmPaulis requested changes

2024-07-30 22:34 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-ced587ab00.engk8s.processmaker.net

2024-07-31 13:20 UTC, pmPaulis requested changes

2024-07-31 13:20 UTC, pmPaulis commented on tests/Fixtures/action_by_email_process.bpmn
> +    <bpmn:task id="node_2" name="Form Task" pm:screenRef="62" pm:allowInterstitial="false" pm:assignment="requester" pm:assignmentLock="false" pm:allowReassignment="false" pm:config="{&#34;web_entry&
This process was created in order to test the function testShowScreen() please don't change the 
screenCompleteRef 
So when the require login is disable this is the correct value `requireLogin&#34;:false`

2024-07-31 13:21 UTC, pmPaulis requested changes

2024-07-31 13:21 UTC, pmPaulis commented on tests/Feature/TaskControllerTest.php
> +    public function testRequireLogin()
Rename the test to testActionByEmailWithRequireLogin

2024-07-31 13:21 UTC, pmPaulis commented on tests/Fixtures/action_by_email_process_require_login.bpmn
> +    <bpmn:task id="node_2" name="Form Task" pm:screenRef="62" pm:allowInterstitial="false" pm:assignment="requester" pm:assignmentLock="false" pm:allowReassignment="false" pm:config="{&#34;web_entry&
please create a process without ScreenComplete and upload this, because th value defined here screenCompleteRef&#34;:null is not correct

2024-07-31 13:23 UTC, pmPaulis requested changes

2024-07-31 13:23 UTC, pmPaulis commented on tests/Feature/TaskControllerTest.php
> +    }
Create a test called `testActionByEmailWithoutRequireLogin`

2024-07-31 20:16 UTC, pmPaulis requested changes

2024-07-31 20:16 UTC, pmPaulis commented on tests/Feature/TaskControllerTest.php
> +    public function testActionBYEmailWithScreen()
Rename to  `testActionByEmailWithScreen`

2024-07-31 20:16 UTC, pmPaulis commented on tests/Fixtures/action_by_email_process.bpmn
> +    <bpmn:task id="node_2" name="Form Task" pm:screenRef="62" pm:allowInterstitial="false" pm:assignment="requester" pm:assignmentLock="false" pm:allowReassignment="false" pm:config="{&#34;web_entry&
please not remove this value `screenCompleteRef` ... this is the purpose of this testActionByEmailWithScreen validate when the screenCompleteRef has a value

2024-07-31 20:22 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-ced587ab00.engk8s.processmaker.net

2024-08-01 14:45 UTC, pmPaulis approved these changes

2024-08-08 15:05 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-ced587ab00.engk8s.processmaker.net

2024-08-09 03:44 UTC, merged