feature/FOUR-18221:  Update the component using the new colors and Ui updates
ProcessMaker/processmaker pull request #7293
Opened 2024-08-28 20:57 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
FOUR-18128 Update the component using the new colors and Ui updates

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-18221

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

2024-08-28 22:01 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-e8268c4129.engk8s.processmaker.net

2024-08-29 12:33 UTC, fagubla requested changes

2024-08-29 12:33 UTC, fagubla commented on resources/js/processes-catalogue/components/BaseChart.vue
> +  background: white;
this chage will affect to all SavedSearch Chart in the Launchpad

2024-08-29 13:57 UTC, fagubla approved these changes

2024-08-29 22:01 UTC, merged