feature/FOUR-18857
ProcessMaker/processmaker pull request #7370
Opened 2024-09-13 16:58 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
Describe the issue this ticket solves and describe how to reproduce the issue (please attach any fixtures used to reproduce the issue).

## Solution
- List the changes you've introduced to solve the issue.

## How to Test
Describe how to test that this solution works.

## Related Tickets & Packages
- Link to any related FOUR tickets, PRDs, or packages

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2024-09-13 18:24 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-e78922b413.engk8s.processmaker.net

2024-09-13 20:18 UTC, fagubla requested changes

2024-09-13 20:18 UTC, fagubla commented on resources/views/requests/show.blade.php
> +    <div class="process-catalog-main" :class="{ 'menu-open': showMenu }">
process-catalog-main?

2024-09-13 20:18 UTC, fagubla commented on resources/views/tasks/edit.blade.php
> +    <div class="process-catalog-main" :class="{ 'menu-open': showMenu }">
same here

2024-09-16 19:05 UTC, fagubla approved these changes

2024-09-17 16:59 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-e78922b413.engk8s.processmaker.net

2024-09-17 17:42 UTC, merged