FOUR-19237: Cases list "Pagination"
ProcessMaker/processmaker pull request #7403
Opened 2024-09-23 19:43 UTC by henryjonathanquispe

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-19237

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2024-09-23 20:19 UTC, fagubla requested changes

2024-09-23 20:19 UTC, fagubla commented on resources/jscomposition/base/table/Pagination.vue
this file is used in the section caseDetail

2024-09-23 20:19 UTC, fagubla commented on resources/jscomposition/system/table/Pagination.vue
> +        'hover:tw-cursor-pointer hover:tw-bg-gray-100': pageModel < pages-1
pages - 1

2024-09-23 20:19 UTC, fagubla commented on resources/jscomposition/system/table/Pagination.vue
> +        'hover:tw-cursor-pointer hover:tw-bg-gray-100': pageModel >0
> 0

2024-09-23 20:19 UTC, fagubla commented on resources/jscomposition/system/table/Pagination.vue
> +        'hover:tw-cursor-pointer hover:tw-bg-gray-100 ': pageModel >0
> 0

2024-09-23 20:19 UTC, fagubla commented on resources/jscomposition/system/table/Pagination.vue
> +        'hover:tw-cursor-pointer hover:tw-bg-gray-100': pageModel < pages-1
pages - 1

2024-09-23 20:19 UTC, fagubla commented on resources/jscomposition/system/table/Pagination.vue
> +
remove blank line

2024-09-23 20:19 UTC, fagubla commented on resources/jscomposition/system/table/Pagination.vue
translation for 'items' is missing

2024-09-23 20:19 UTC, fagubla commented on resources/jscomposition/base/table/TCell.vue
> +      console.log("BREAK POINT AQUIII renderer");
remove console

2024-09-24 11:48 UTC, fagubla requested changes

2024-09-24 11:48 UTC, fagubla commented on resources/jscomposition/base/table/Pagination.vue
This file is used in Case Detail

2024-09-24 13:15 UTC, henryjonathanquispe commented on resources/jscomposition/base/table/Pagination.vue
The file has customizations for the platform

2024-09-24 14:51 UTC, fagubla approved these changes

2024-09-24 16:56 UTC, merged