FOUR-19328: Enable the order desc/asc "Tasks" tab
ProcessMaker/processmaker pull request #7416
Opened 2024-09-25 20:28 UTC by henryjonathanquispe

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-19328

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next

2024-09-25 22:06 UTC, pmPaulis requested changes

2024-09-25 22:06 UTC, pmPaulis commented on resources/jscomposition/cases/casesDetail/api/index.js
> +        url: "http:\/\/localhost:8092\/api\/1.0\/tasks-by-case?page=1",
The URL is harcoded localhost:8092

2024-09-25 22:06 UTC, pmPaulis commented on resources/jscomposition/cases/casesDetail/api/index.js
> +    path: "http:\/\/localhost:8092\/api\/1.0\/tasks-by-case",
The URL is harcoded localhost:8092

2024-09-26 12:14 UTC, fagubla requested changes

2024-09-26 12:14 UTC, fagubla commented on resources/jscomposition/system/table/SortTable.vue
> +
remove extra line

2024-09-26 12:14 UTC, fagubla commented on resources/jscomposition/system/table/SortTable.vue
> +        :state="indexFilter == index? 'asc': ''"
add an space after index

2024-09-26 12:14 UTC, fagubla commented on resources/jscomposition/system/table/filter/sortableFilter/SortableFilter.vue
> +    }"
this would be in a single line

2024-09-26 16:02 UTC, fagubla requested changes

2024-09-26 16:02 UTC, fagubla commented on resources/jscomposition/base/table/THeader.vue
> +<style>
styles must be scoped

2024-09-26 16:19 UTC, fagubla approved these changes

2024-09-26 19:15 UTC, merged