feature/FOUR-18630
ProcessMaker/processmaker pull request #7438
Opened 2024-09-30 14:29 UTC by luNunezProcessmaker

## Issue & Reproduction Steps
FOUR-18498: FE: Needs to collpase/descollapse according the flag saved

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-18630

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

2024-09-30 19:59 UTC, pmPaulis requested changes

2024-09-30 19:59 UTC, pmPaulis commented on resources/js/processes-catalogue/components/ProcessesCatalogue.vue
> +        });
add a catch to get errors from the API

2024-09-30 19:59 UTC, pmPaulis commented on resources/js/processes-catalogue/components/ProcessesCatalogue.vue
> +          },
add .catch when the API give an error

2024-09-30 20:07 UTC, fagubla requested changes

2024-09-30 20:07 UTC, fagubla commented on resources/js/processes-catalogue/components/ProcessesCatalogue.vue
> +        });
is there a possibility to get the entire configuration from the Controller?
So we avoid making several Call to API

2024-10-01 16:53 UTC, fagubla approved these changes

2024-10-01 17:10 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-4317444e89.engk8s.processmaker.net

2024-10-01 19:13 UTC, merged