Feature/four 19330
ProcessMaker/processmaker pull request #7447
Opened 2024-10-01 20:50 UTC by luNunezProcessmaker

## Issue & Reproduction Steps

Work was done on adapting some columns and changing the table to perform the sort

at the same time the call of the data with the new `/requests-by-case?case_number=` API
FOUR-18139: Enable the order desc/asc "Requests" tab

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-19330

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

2024-10-01 21:43 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-3742593f62.engk8s.processmaker.net

2024-10-01 23:32 UTC, pmPaulis requested changes

2024-10-01 23:32 UTC, pmPaulis commented on resources/jscomposition/cases/casesDetail/config/columns.js
>    header: "Request #",
Please update to `Request ID`
![image](https://github.com/user-attachments/assets/1664711a-887a-4617-8e7d-f16c78d3a73b)

2024-10-01 23:32 UTC, pmPaulis commented on resources/jscomposition/cases/casesDetail/config/columns.js
>  const requestNameColumn = () => ({
This column does not exist
![image](https://github.com/user-attachments/assets/1664711a-887a-4617-8e7d-f16c78d3a73b)

2024-10-01 23:32 UTC, pmPaulis commented on resources/jscomposition/cases/casesDetail/config/columns.js
The column participants is missing
![image](https://github.com/user-attachments/assets/1664711a-887a-4617-8e7d-f16c78d3a73b)

2024-10-02 12:13 UTC, fagubla requested changes

2024-10-02 12:13 UTC, fagubla commented on resources/jscomposition/cases/casesDetail/api/index.js
> -  }
we still using this method

2024-10-02 14:09 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-3742593f62.engk8s.processmaker.net

2024-10-02 14:25 UTC, pmPaulis requested changes

2024-10-02 14:25 UTC, pmPaulis commented on resources/jscomposition/cases/casesDetail/config/columns.js
>  const requestNumberColumn = () => ({
update to requestIdColumn

2024-10-02 14:25 UTC, pmPaulis commented on resources/jscomposition/cases/casesDetail/config/columns.js
> +const processNameColumnRequest = () => ({
update to `processNameColumn`

2024-10-02 14:25 UTC, pmPaulis commented on resources/jscomposition/cases/casesDetail/config/columns.js
>  const currentTaskColumn = () => ({
Update to `TaskColumn`

2024-10-02 14:25 UTC, pmPaulis commented on resources/jscomposition/cases/casesDetail/config/columns.js
>    header: "started",
Please update to `Started`

2024-10-02 14:54 UTC, pmPaulis approved these changes

2024-10-02 21:11 UTC, pmPaulis approved these changes

2024-10-02 21:11 UTC, merged