FOUR-19753 : The task comments is not showing the buttons to register the comments
ProcessMaker/processmaker pull request #7616
Opened 2024-10-23 20:15 UTC by henryjonathanquispe

## Issue & Reproduction Steps
1. Open a task ->  /task
2. Go to comments tab
3. Tried to add a comments

## Solution
- Change the css styles in the view

## How to Test
1. Open a task
2. Verify the tab comments and tried to add a comment

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-19753

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2024-10-23 20:29 UTC, fagubla requested changes

2024-10-23 20:29 UTC, fagubla commented on resources/views/tasks/edit.blade.php
> +  <div id="task" v-cloak class="tw-flex tw-w-full tw-grow">
this must be in multiple lines

2024-10-23 20:29 UTC, fagubla commented on resources/views/tasks/edit.blade.php
> +      <div v-cloak class="tw-flex tw-w-full tw-grow">
multiple lines

2024-10-23 20:29 UTC, fagubla commented on resources/views/tasks/edit.blade.php
how this is working with intercom?

2024-10-23 20:29 UTC, fagubla commented on resources/jscomposition/base/form/Dropdown.vue
> +      type: [Object, null],
null?
is not better use required as false

2024-10-23 20:29 UTC, fagubla commented on resources/jscomposition/cases/casesMain/utils/filters.js
> +    if (e.field === "case_status") {
which meas 'e'

2024-10-23 23:42 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-5107741f4d.engk8s.processmaker.net

2024-10-24 15:05 UTC, fagubla requested changes

2024-10-24 15:05 UTC, fagubla commented on resources/views/tasks/edit.blade.php
use a correct code style

2024-10-24 18:35 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-5107741f4d.engk8s.processmaker.net

2024-10-24 19:49 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-5107741f4d.engk8s.processmaker.net

2024-10-24 21:35 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-5107741f4d.engk8s.processmaker.net

2024-10-28 18:51 UTC, fagubla approved these changes

2024-10-29 16:29 UTC, merged