FOUR-19807 : Task column should be display the last active task (or tasks if are possible)
ProcessMaker/processmaker pull request #7664
Opened 2024-10-31 17:23 UTC by henryjonathanquispe

"Task" column should be display the last task (or tasks if are possible), Currently is displaying always the first task.
In the next process the token is in the third task the previous two tasks were completed. The name of the first task is displayed always.
'status' => 'ACTIVE',

## Issue & Reproduction Steps
1. Go to cases
2 check the columns tasks

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-19807

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy

2024-10-31 18:08 UTC, fagubla requested changes

2024-10-31 18:08 UTC, fagubla commented on resources/jscomposition/cases/casesMain/config/columns.js
> +
remove blank line

2024-10-31 18:08 UTC, fagubla commented on resources/jscomposition/system/table/cell/TruncatedOptionsCell.vue
> +                :href="href(option)">
a possible conflict with another ticket

2024-10-31 18:17 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-cfabed5275.engk8s.processmaker.net

2024-10-31 18:42 UTC, fagubla approved these changes

2024-10-31 19:16 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-cfabed5275.engk8s.processmaker.net

2024-11-06 14:03 UTC, pmPaulis commented
This changes has a lot of conflicts, in this way a new PR was created using the last changes `release-2024-fall`

2024-11-06 14:05 UTC, closed without merging