FOUR-19949: Upgrade is taking about 17 minutes for 300k requests 2024_10_08_113301_populate_comments_case_number
ProcessMaker/processmaker pull request #7668
Opened 2024-10-31 19:49 UTC by pmPaulis

## Issue & Reproduction Steps
Upgrade is taking about 17 minutes for 300k requests 2024_10_08_113301_populate_comments_case_number

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-19949

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2024-10-31 20:00 UTC, caleeli commented
@pmPaulis the migration dies:

![image](https://github.com/user-attachments/assets/37b8c3dc-9e3a-4ea2-b291-0abe2fdcfb89)

2024-10-31 20:01 UTC, caleeli requested changes
Review the error raised:
```
  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:822
    818▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    819▕                 );
    820▕             }
    821▕ 
  ➜ 822▕             throw new QueryException(
    823▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    824▕             );
    825▕         }
    826▕     }

  1   vendor/laravel/framework/src/Illuminate/Database/Connection.php:580
      PDOException::("SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'case_number' at row 1")

  2   vendor/laravel/framework/src/Illuminate/Database/Connection.php:580
      PDOStatement::execute()

  3   vendor/laravel/framework/src/Illuminate/Database/Connection.php:809
      Illuminate\Database\Connection::Illuminate\Database\{closure}()

  4   vendor/laravel/framework/src/Illuminate/Database/Connection.php:776
      Illuminate\Database\Connection::runQueryCallback()

  5   vendor/laravel/framework/src/Illuminate/Database/Connection.php:569
      Illuminate\Database\Connection::run()

  6   vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:469
      Illuminate\Database\Connection::statement()

  7   vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:355
      Illuminate\Database\DatabaseManager::__call()

  8   upgrades/2024_10_08_113301_populate_comments_case_number.php:77
      Illuminate\Support\Facades\Facade::__callStatic()

  9   vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php:53
      PopulateCommentsCaseNumber::{closure}()

  10  upgrades/2024_10_08_113301_populate_comments_case_number.php:66
      Illuminate\Database\Query\Builder::chunk()

  11  vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:493
      PopulateCommentsCaseNumber::up()

  12  vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:410
      Illuminate\Database\Migrations\Migrator::runMethod()

  13  vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:419
      Illuminate\Database\Migrations\Migrator::Illuminate\Database\Migrations\{closure}()

  14  ProcessMaker/Upgrades/UpgradeMigrator.php:77
      Illuminate\Database\Migrations\Migrator::runMigration()

  15  vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:181
      ProcessMaker\Upgrades\UpgradeMigrator::runUp()

  16  vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:124
      Illuminate\Database\Migrations\Migrator::runPending()

  17  ProcessMaker/Upgrades/Commands/UpgradeCommand.php:63
      Illuminate\Database\Migrations\Migrator::run()

  18  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
      ProcessMaker\Upgrades\Commands\UpgradeCommand::handle()

  19  vendor/laravel/framework/src/Illuminate/Container/Util.php:41
      Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()

  20  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
      Illuminate\Container\Util::unwrapIfClosure()

  21  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:35
      Illuminate\Container\BoundMethod::callBoundMethod()

  22  vendor/laravel/framework/src/Illuminate/Container/Container.php:662
      Illuminate\Container\BoundMethod::call()

  23  vendor/laravel/framework/src/Illuminate/Console/Command.php:211
      Illuminate\Container\Container::call()

  24  vendor/symfony/console/Command/Command.php:326
      Illuminate\Console\Command::execute()

  25  vendor/laravel/framework/src/Illuminate/Console/Command.php:180
      Symfony\Component\Console\Command\Command::run()

  26  vendor/symfony/console/Application.php:1096
      Illuminate\Console\Command::run()

  27  vendor/symfony/console/Application.php:324
      Symfony\Component\Console\Application::doRunCommand()

  28  vendor/symfony/console/Application.php:175
      Symfony\Component\Console\Application::doRun()

  29  vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:201
      Symfony\Component\Console\Application::run()

  30  artisan:30
      Illuminate\Foundation\Console\Kernel::handle()
```

2024-10-31 20:50 UTC, pmPaulis commented
@caleeli 
I added some validation then when i execute the command or upgrade the following is returns:
```
php artisan processmaker:update-comments-case-number
36 comments updated in this chunk related to ProcessRequestToken
108 comments updated in this chunk related to ProcessRequest
Comments case_number updated successfully
``` 

```
php artisan upgrade

   INFO  Running migrations.  

Preflight Check: 2024_10_08_113301_populate_comments_case_number
Preflight Check Successful: 2024_10_08_113301_populate_comments_case_number
Upgrading: 2024_10_08_113301_populate_comments_case_number
Upgraded:  2024_10_08_113301_populate_comments_case_number (0.01 seconds)
Preflight Check: 2024_10_16_152320_migrate_screen_translations
Preflight Check Successful: 2024_10_16_152320_migrate_screen_translations
Upgrading: 2024_10_16_152320_migrate_screen_translations
Upgraded:  2024_10_16_152320_migrate_screen_translations (0 seconds)
```

2024-11-04 17:47 UTC, caleeli approved these changes

2024-11-05 21:08 UTC, merged