FOUR-20013 | Apply Translation Error When a ‘Cancel Screen’ is Configured
ProcessMaker/processmaker pull request #7711
Opened 2024-11-07 20:49 UTC by mcraeteisha

# Issue
Ticket: [FOUR-20013](https://processmaker.atlassian.net/browse/FOUR-20013)

When a cancelled Request with a configured 'Cancel Screen' is opened, an 'Undefined array key `screen_id`' error is shown.

# Solution
- In the `applyTranslations` function in `ScreenTranslation.php`, change `$screen['screen_id']` to `$screen['id']`. `screen_id` does not exist on `$screen`.

# How to Test
1. Go to branch `observation/FOUR-20013` in `processmaker`.
2. Go to Designer → Screens. Create a Display Screen.
3. Go to Designer → Processes. Create a Process.
4. Configure your Screen as the 'Cancel Screen'.
5. Add a Start Event, Task, and End Event to the Process. Configure the Task. (It does not matter what Screen is used for the Task.)
6. Start a Case.
7. Cancel the Case.
8. Open the Request.
	- The 'Cancel Screen' should display in the Request Summary. There should be no error message.

ci:deploy

# Code Review Checklist

- [ ]  I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ]  This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ]  This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ]  This solution fixes the bug reported in the original ticket.
- [ ]  This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ]  This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ]  This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ]  This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ]  This ticket conforms to the PRD associated with this part of ProcessMaker.

2024-11-07 21:29 UTC, tokensPM commented
QA server K8S was successfully deployed https://ci-443dfacb83.engk8s.processmaker.net

2024-11-13 14:46 UTC, agustinbusso requested changes

2024-11-13 14:46 UTC, agustinbusso commented on ProcessMaker/Traits/TaskResourceIncludes.php
> +        \Log::info('includeScreen');
Please remove this log

2024-11-13 14:50 UTC, agustinbusso approved these changes

2024-11-13 20:35 UTC, merged