FOUR-20583: S2: Improve vendors
ProcessMaker/processmaker pull request #7798
Opened 2024-12-05 18:17 UTC by henryjonathanquispe

## Solution
- Create chunks for vendor.js in webpack.js

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-20583

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy

2024-12-19 22:41 UTC, nolanpro commented
@pmPaulis @henryjonathanquispe Here are my initial notes and questions:
- loader*.js files have a lot of duplication. You could extract to a common folder and wrap the differences in if statements and call it like this
 ```
import { initializeCommonLoader } from "../next/commonLoader";
import sharedComponents from "../next/libraries/sharedComponents";
import vueFormElements from "../next/libraries/vueFormElements";

initializeCommonLoader({
  includeScreenBuilder: true,
  includeModeler: false,
  includeMonaco: false,
});
```
- is accesibility.js being used anywhere?
- If we make any changes to the logic in bootstrap.js and app-layout.js, do we need to duplicate that logic in the next folder until the entire app is converted to use the new code?
- - What’s the purpose of the badPractices.js file?

2025-01-09 17:32 UTC, pmPaulis commented
@henryjonathanquispe 
Please consider review the @nolanpro comments 

- Improve the loader*.js
- Remove accesibility.js because is not used (it was removed)
- Remove the badPractices.js and move this to the document created.

Regards,

2025-01-13 20:48 UTC, pmPaulis approved these changes

2025-01-14 17:18 UTC, henryjonathanquispe commented on resources/views/layouts/sidebar.blade.php
> +      v-b-tooltip.hover.right="{ title: 'Expand sidebar', animation: false, boundary: 'viewport', delay: { show: 0, hide: 0 } }"
@caleeli I updated the PR, restore the changes

2025-01-16 19:18 UTC, pmPaulis commented
**PR's Packages**
https://github.com/ProcessMaker/package-webentry/pull/269
https://github.com/ProcessMaker/connector-docusign/pull/55

2025-01-23 17:17 UTC, pmPaulis commented
@henryjonathanquispe 
the PR has conflicts with the following PR
https://github.com/ProcessMaker/processmaker/pull/7873/files

2025-01-23 18:08 UTC, pmPaulis requested changes

2025-01-23 18:08 UTC, pmPaulis commented on resources/views/tasks/edit.blade.php
> -              }
@henryjonathanquispe the new code was added here https://github.com/ProcessMaker/processmaker/pull/7873/files

2025-01-23 19:12 UTC, pmPaulis commented
@ryancooley @boliviacoca 
This PR has the following Failing in the unit test, this is not related with the changes but we will review in a specific ticket.

```
Filter (Tests\Filter)
 ✘ Compare data integer
   │
   │ Failed asserting that actual size 2 matches expected size 1.
   │
   │ /opt/processmaker/tests/unit/ProcessMaker/FilterTest.php:88
   │ /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:176
   │
```

2025-01-23 19:36 UTC, pmPaulis approved these changes

2025-01-23 20:09 UTC, merged