Feature/FOUR-20550: [20298] Create new page home screen as Layout (List Pane and New Home Container)
ProcessMaker/processmaker pull request #7846
Opened 2024-12-19 15:58 UTC by CarliPinell

## Solution

- ProcessDashboardsMenu component was implemented with Router-View to call isolated components for Process Container And Dashboard Viewer  from left Processes and Dashboard menu pane.

## How to Test
- Login PM4
- Go to Tasks
- In left side Pane Choose some Draft Options for Processes or Dashboards
- Different components will be rendered in the main container

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-20550

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

2024-12-19 18:13 UTC, pmPaulis requested changes

2024-12-19 18:14 UTC, pmPaulis commented
@CarliPinell 
Your branch is requesting have installed save search, is this correct?
![Captura de pantalla 2024-12-19 a las 1 24 54 p  m](https://github.com/user-attachments/assets/3fab4a9f-ffff-4aff-adc0-b492d148f923)

Regards,

2024-12-19 18:53 UTC, CarliPinell commented on resources/js/tasks/components/DashboardViewer.vue
> +        <p v-else>No selected dashboard</p>
Those <div> and <h2> tags will be removed when DashboardViewer.vue component has the official content. For now is only Draft.

2024-12-19 18:53 UTC, CarliPinell commented on resources/js/tasks/components/DashboardViewer.vue
> +        <h2>Dashboard Viewer</h2>
Those <div> and <h2> tags will be removed when DashboardViewer.vue component has the official content. For now is only Draft.

2024-12-20 19:28 UTC, pmPaulis approved these changes

2025-01-08 17:13 UTC, nolanpro approved these changes

2025-01-14 18:40 UTC, CarliPinell commented
This Pull Request was closed in order to be replaced with another PR that contains the necessary code. https://github.com/ProcessMaker/processmaker/pull/7897

2025-01-14 18:40 UTC, closed without merging

2025-01-14 18:40 UTC, CarliPinell commented
This Pull Request was closed in order to be replaced with another PR that contains the necessary code. https://github.com/ProcessMaker/processmaker/pull/7897